mongodb/docs-app-services

source/authentication.txt, source/reference/authenticate-http-client-requests.txt
- https://jira.mongodb.org/browse/DOCSP-22534
- [Authenticate HTTP Client Requests/Refresh a Client API Access Token](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-22534/reference/authenticate-http-client-requests/#refresh-a-client-api-access-token)
[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)
=> (DOCSP-22534): Add information about refresh token expiration

.github/issue_template.md, .github/pull_request_template.md, README.md, REVIEWING.md, snooty.toml
Add a handful of stuff to set up the repo like we had it for docs-realm, including:
- Issue template
- Pull request template
- REVIEWING.md
- Applicable info from the README.md
- Update the "container pages" to expand via snooty.toml
=> Add configuration details for repo

Makefile
Per the instructions on [how to set up Pushless Staging](https://wiki.corp.mongodb.com/x/EZipBg), this Makefile will enable us to use pushless staging with the app-services repo.
=> Add Makefile to enable pushless staging

source/sync/learn/overview.txt
Remove beta/preview from Flutter and Kotlin SDK names. not necessary here and prone to get out of date, as the labels for both Flutter and Kotlin currently are. 
n/a
=> Remove beta/preview from Flutter and Kotlin SDK names

source/graphql.txt, source/graphql/types-and-resolvers.txt
- (DOCSP-11203): GraphQL RelationInput cannot simultaneously create and link
- (DOCSP-19374): GraphQL FindMany limit has a default of 100
- (DOCSP-22884): GraphQL mutations and custom resolvers use transactions
- (DOCSP-21985): GraphQL represents undefined as an empty object
- [GraphQL API](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/graphql/graphql)
- [GraphQL Types, Resolvers, & Operators](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/graphql/graphql/types-and-resolvers/)
=> GraphQL Updates

source/authentication.txt, source/includes/refresh-token-expiration.rst, source/reference/authenticate-http-client-requests.txt
A few weeks ago, I added refresh token expiration length to the docs based on this Jira ticket: https://jira.mongodb.org/browse/DOCSP-22534
This ticket has been re-opened, because the expiration length (30 days) I previously added to the docs was incorrect. After some spelunking in the backend auth code, I've updated the docs based on what I found.
- [Authentication/User Sessions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/update-inaccurate-refresh-token-length/authentication/#user-sessions)
- [Authenticate HTTP Client Requests/Refresh a Client API Access Token](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/update-inaccurate-refresh-token-length/reference/authenticate-http-client-requests/#refresh-a-client-api-access-token) …
=> Update refresh token expiration length based on backend auth code

source/functions/mongodb/read.txt
- (DOCSP-23041): Functions find example wrongly shows insertMany
- [Read Data > Find One or More Documents](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/fix-example/functions/mongodb/read/#find-one-or-more-documents--find---)
=> (DOCSP-23041): Functions find example wrongly shows insertMany

docs-release-notes.md
Moving App Services docs release notes to their own file in the App Services Docs repo. It makes sense for these records to live alongside the docs in this repository, instead of over in the Realm docs repo.
=> (DOCSP-23215): Add docs release notes for w/e June 10, 2022

source/functions/javascript-support.txt, source/functions/mongodb/api.txt, source/services/aws.txt
- Noticed this issue in a separate PR. Looks like these got butchered in https://github.com/mongodb/docs-app-services/commit/c2a0cbe4396ae4f5fb858d5686fc6700b8480abe
- Guess [which jerk](https://github.com/mongodb/docs-app-services/pull/54#pullrequestreview-1001880870) approved THAT PR?
- [MongoDB API](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/fix-monospace-method-titles/functions/mongodb/api/)
=> Fix monospace method titles in MongoDB API spec

source/triggers/database-triggers.txt
Updated note in the section "Use Project Expressions to Reduce Input Data Size", so that what was previously written as "operation_type" is updated to read as operationType, matching the example right below it where the field has to be in camel case.
- https://jira.mongodb.org/browse/DOCS-15429
- [Database Triggers](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCS-15429/triggers/database-triggers/#use-project-expressions-to-reduce-input-data-size/)
=> (DOCS-15429): Fixed typo on Database Triggers page

source/sync/data-access-patterns/flexible-sync-permissions-guide.txt
Re-add secret template app info.
Unfortunately, until https://jira.mongodb.org/browse/BAAS-14445 is resolved, 2/3 templates don't work unless you notice and follow the big caveat.
---
This reverts commit a186b8c315d0dde88fcc9fc8df9a7e8a2e280d4d.
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/templates/sync/data-access-patterns/flexible-sync-permissions-guide/
=> Revert "Hide flex sync permissions template apps info - temporary (#49)"

source/index.txt, source/reference.txt
move admin api from reference folder in sidebar to top level. i think this is an important and well document feature worth not hiding in the reference folder
- n/a
- [see sidebar, toward bottom](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin_api_up_in_sidebar/)
=> Move Admin API up in sidebar

source/manage-apps/configure/config.txt
Added a note/section to the CLI docs landing page to warn for reserved file names users shouldn't use. DRAFT.
- https://jira.mongodb.org/browse/DOCSP-23435
- [App Configuration](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-23435/manage-apps/configure/config/)
=> (DOCSP-23435): Reserved File Names Warning

source/mongodb/limitations-serverless-instances.rst
Updated the section of "MongoDB Data Sources" which lists some limitations of using serverless as a data source because of the lack of change streams to also mention that watching collections is  unavailable.
- https://jira.mongodb.org/browse/DOCSP-23473
- [MongoDB Data Sources](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-23473/mongodb/)
=> (DOCSP-23473): Updated Severless Limitations to Include Incompatibility with Watch-for-Changes

source/graphql.txt, source/graphql/authenticate.txt, source/graphql/cli.txt, source/graphql/expose-data.txt
- fix naming to be 'Atlas GraphQL API' on first mention on page, to be consistent w the [naming guidance](https://docs.google.com/document/d/196sHKMtqpXQCdTF7AG_b989_osmmgbs9fu3KGyGgBEU/edit)
- shift IA to put pages in order of use/relevance. added link to Apollo GraphQL guide
- https://jira.mongodb.org/browse/DOCSP-23637
- [GraphQL](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-23637/graphql)
=> (DOCSP-23637): GraphQL naming/IA refresh

source/sync/configure/optimize-sync-atlas-usage.txt
- https://jira.mongodb.org/browse/DOCSP-23722
- [Optimize Sync Atlas Usage](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-23722/sync/configure/optimize-sync-atlas-usage/) -- new "trimming" section, removed notes about Flexible Sync non-support for advanced backend compaction, added sentences about CMOT enabled by default at 30 days.
=> (DOCSP-23722): Documentation for Flexible Sync History Trimming

source/manage-apps/configure/config/data_sources.txt, source/rules/roles.txt
"Default" is misspelled "defaut" twice on the MongoDB Data Source Configuration Files page. I also found another page (roles.txt) with this same error and also corrected that one. If that should be on another ticket/PR let me know!
- https://jira.mongodb.org/browse/DOCSP-23592
- [MongoDB Data Source Configuration Files
](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-23592/manage-apps/configure/config/data_sources/)
=> (DOCSP-23592): Fixed "Defaut" Typo

source/authentication.txt, source/includes/apple-account-deletion-requirements.rst
- https://jira.mongodb.org/browse/DOCSP-20091
- [Users & Authentication/User Accounts](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-20091/authentication/#user-accounts): Add the include that mentions folks distributing through the App Store must implement account deletion. Also, update include to remove the date because we are past the date and so now all apps must include it.
=> (DOCSP-20091): Add Apple requirements to user accounts, update include

source/graphql.txt
- (DOCSP-24152): No GraphQL relationships for object array fields
- [PAGE_NAME](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/graphql-relationship-limitations/graphql/#limitations)
=> (DOCSP-24152): No GraphQL relationships for object array fields

source/includes/tip-role-order-config-files.rst, source/manage-apps/configure/config/sync.txt, source/sync/data-access-patterns/permissions.txt
- (DOCSP-23201): Flexible sync type-specific & field-level permissions
- [Flexible Sync Configuration](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/sync-rules/manage-apps/configure/config/sync/#flexible-sync-configuration)
- [Session Roles](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/sync-rules/sync/data-access-patterns/permissions/#session-roles)
=> (DOCSP-23201): Flexible sync type-specific & field-level permissions

source/schemas/relationships.txt
Adds a note in addition to https://github.com/mongodb/docs-app-services/pull/117
(DOCSP-24152): No GraphQL relationships for object array fields
- [Relationships > Embedded Object Within a List](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/gql-relationship/schemas/relationships/#embedded-object-within-a-list)
=> (DOCSP-24152): No GraphQL relationships for object array fields (pt 2)

source/manage-apps/configure/config/template-expansions.txt
- (DOCSP-24229): Template configurations use non-existent --environment flag
- [Create Template Configurations with Expansions > Specify an Environment](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/env/manage-apps/configure/config/template-expansions/)
=> (DOCSP-24229): Template configurations use non-existent --environment flag

source/sync/data-access-patterns/permissions.txt
Based on a Slack request.
- [Sync Rules and Permissions -> Collection-Level Rules](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/recover-collection-based-permissions/sync/data-access-patterns/permissions/#collection-level-rules): Recovered section pertaining to Collection-Level Rules, with some tweaks based on how the page has changed between when we lost the section and now.
=> Recover custom collection rules

source/sync/learn/overview.txt
Clarified in a note on the Overview Device Sync overview page that the Realm Web SDK doesn't support Atlas Device Sync.
- https://jira.mongodb.org/browse/DOCSP-23964
- [PAGE_NAME](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-23964/sync/learn/overview/)
=> (DOCSP-23964): Clarify that the Realm Web SDK doesn't support Atlas Device Sync

source/manage-apps/secure.txt
- (DOCSP-25418) Add Data API & GraphQL to TLS Security
- [Security > Transport Layer Security (TLS)](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/api-tls/manage-apps/secure/#transport-layer-security--tls-)
=> (DOCSP-25418) Add Data API & GraphQL to TLS Security

source/includes/trigger-project-expression.rst
- (DOCSP-24936) [BAAS] Allow exclusions in projection expressions in triggers
- [Database Triggers](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/exclusions/triggers/database-triggers/)
=> (DOCSP-24936) [BAAS] Allow exclusions in projection expressions in triggers

source/manage-apps/deploy/automated/deploy-automatically-with-github.txt
remove note that is:
- out of date with realm-cli v1 related guidance
- inaccurate about realm-cli v2
- generally confusing
- https://jira.mongodb.org/browse/DOCSP-20113
- [Deploy Automatically with Github](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-20113/manage-apps/deploy/automated/deploy-automatically-with-github/)
=> (DOCSP-20113): Remove out-of-date, inaccurate note

source/hosting.txt, source/hosting/enable-hosting.txt, source/includes/note-static-hosting-requires-paid-tier-cluster.rst
- (DOCSP-24761) [BAAS] Limit enabling hosting to users who have a linked paid cluster
- [Static Hosting](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/paid-hosting/hosting/)
- [Enable Hosting](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/paid-hosting/hosting/enable-hosting/)
=> (DOCSP-24761) [BAAS] Limit enabling hosting to users who have a linked paid cluster

source/includes/destructive-schema-change-app-update.rst, source/manage-apps/configure/config/sync.txt, source/sync/configure/enable-sync.txt, source/sync/configure/pause-or-terminate-sync.txt, source/sync/data-access-patterns/flexible-sync.txt, source/sync/data-model/update-schema.txt, source/sync/error-handling/client-resets.txt, source/sync/error-handling/errors.txt
- https://jira.mongodb.org/browse/DOCSP-25395
- [Atlas Device Sync Configuration Files](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-25395/manage-apps/configure/config/sync/)
- [Enable Atlas Device Sync](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-25395/sync/configure/enable-sync/)
- [Pause or Terminate Sync](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-25395/sync/configure/pause-or-terminate-sync/)
- [Update Your Schema](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-25395/sync/data-model/update-schema/)
- [Client Resets](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-25395/sync/error-handling/client-resets/) …
=> (DOCSP-25395): Update App Services docs for Client Reset with Recovery

source/functions/javascript-support.txt
- Also alphabetize the object table
- https://jira.mongodb.org/browse/DOCSP-25790
- https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/bigint/functions/javascript-support/#built-in-objects
=> (DOCSP-25790): Add BigInt to list of unsupported JS objects

source/includes/deployment-region-auth-callback-urls.rst
- https://jira.mongodb.org/browse/DOCSP-23902
- [Facebook Authentication](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-23902-url-fix/authentication/facebook/)
=> (DOCSP-23902): Global URL small fix on Facebook Authentication page

source/release-notes/changelogs/backend/changelog-backend-2022.rst
19 October 2022 release notes.
Must be merged after https://github.com/mongodb/docs-app-services/pull/186 b/c uses a ref introduced in that PR.
- https://jira.mongodb.org/browse/DOCSP-25908
- [Release notes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-25908/release-notes/backend)
=> (DOCSP-25908): 19 October 2022 release notes

source/billing.txt
Remove bolded text after link to address Snooty Platform bug (see https://jira.mongodb.org/browse/DOP-3330)
note: looked throughout rest of docs for similar error pattern of link + bold, and didn't find anything.
- https://jira.mongodb.org/browse/DOCSP-26070
- [Billing](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26070/billing/)
=> (DOCSP-26070): Remove bolded text after link

source/mongodb/crud-and-aggregation-apis.txt
- (DOCSP-25878) Arrayfilters is noted in the unsupported options even though it is supported
- [CRUD & Aggregation APIs](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/arrayFilters/mongodb/crud-and-aggregation-apis/)
=> (DOCSP-25878) Arrayfilters is noted in the unsupported options even though it is supported

source/sync/data-access-patterns/permissions.txt
- https://jira.mongodb.org/browse/DOCSP-25812
- [Sync Rules and Permissions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-25812-add-stringToOid-flex-sync/sync/data-access-patterns/permissions/#expressions) 
=> (DOCSP-25812): Updating read/write device sync permissions for %stringToOid

source/sync/data-access-patterns/flexible-sync-permissions-guide.txt
- https://jira.mongodb.org/browse/DOCSP-26248
- [Flexible Sync Permissions Guide](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26248/sync/data-access-patterns/flexible-sync-permissions-guide/): Update permissions template app names throughout page
=> (DOCSP-26248): Correct the Flex Sync permissions template names

source/authentication/apple.txt, source/authentication/custom-function.txt, source/authentication/custom-jwt.txt, source/authentication/email-password.txt, source/authentication/facebook.txt, source/authentication/google.txt
Add Flutter SDK to tabs about the various auth providers. 
- https://jira.mongodb.org/browse/DOCSP-26263
- [Apple Auth](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26263/authentication/apple/)
- [Custom Function Auth](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26263/authentication/custom-function/)
- [Facebook Auth](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26263/authentication/facebook/)
- [Custom JWT Auth](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26263/authentication/custom-jwt/)
- [Google Auth](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26263/authentication/google/) …
=> (DOCSP-26263): Add Flutter to authentication tabs

source/release-notes/changelogs/backend/changelog-backend-2022.rst
App Services release notes for Nov. 3, 2022 release.
- https://jira.mongodb.org/browse/DOCSP-26250
- [Release Notes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26250/release-notes/backend/)
=> (DOCSP-26250): App Services release notes 03-11-2022

source/tutorial/flutter.txt
Update tutorial to not delete all app data. This step is no longer necessary b/c of a bug fix in Realm Flutter SDK v0.6.0+beta.
This change **must** be merged after the changes from https://github.com/mongodb-university/realm-template-apps/pull/102 have been deployed for use in the Realm CLI. (However, the changes don't need to be merged in tandem, b/c the tutorial as currently documented still works with the previous version..just the app deletion step is no longer necessary.)
- https://jira.mongodb.org/browse/DOCSP-26228
- [Flutter Device Sync Tutorial](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26228/tutorial/flutter/)
=> (DOCSP-26228): Update tutorial to not delete all app data

source/reference/template-apps.txt
- The iOS UIKit template client is no longer compatible with the SwiftUI backend. The former uses PBS while the latter uses FS.
- TBD whether to support UIKit + FS.
- 
- 
=> Remove iOS template note

source/openapi-admin-v3.yaml
- https://jira.mongodb.org/browse/DOCSP-26247
- Corrected links in Admin API doc sections:
- [Data API](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26247-update-data-api-link/admin/api/v3/#tag/data-api)
- [GraphQL API](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26247-update-data-api-link/admin/api/v3/#tag/graphql)
=> (DOCSP-26247): Correcting link to Data API configuration object ref

source/sync/error-handling/client-resets.txt
Add Flutter SDK client reset tab to Device Sync docs.
Note: do not merge until after https://github.com/mongodb/docs-realm/pull/2266 has been merged & deployed. otherwise ref won't work.
- https://jira.mongodb.org/browse/DOCSP-24570
- [Client Resets](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-24570/sync/error-handling/client-resets/)
=> (DOCSP-24570): Add Flutter client reset tab

source/authentication/api-key.txt
Clarify API auth methods.
- Add more details about difference between server and user api keys. 
- reorganize page
- mention how API key users have special user object property
- add docs on using Admin API to create a server API key
- https://jira.mongodb.org/browse/DOCSP-26045
- [API Key Auth](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26045/authentication/api-key/)
=> (DOCSP-26045): Clarify API auth methods

source/authentication/anonymous.txt, source/authentication/api-key.txt, source/authentication/email-password.txt, source/includes/auth-provider-config-same-name-and-type.rst, source/openapi-admin-v3.yaml
- Small additions for clarity in this PR. In future we should do more work to refresh all of the auth provider pages + auth provider openapi defs
- (DOCSP-26214) Auth provider name must be the same as type
- [Anonymous Auth](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/authproviders/authentication/anonymous/)
- [Email/Password Auth](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/authproviders/authentication/email-password/)
- [API Key Auth](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/authproviders/authentication/api-key/)
- [OpenAPI > Authentication Providers](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/authproviders/admin/api/v3/#tag/authproviders) …
=> (DOCSP-26214) Auth provider name must be the same as type

redocly.yaml
Turns off lint rules that emitted the following warnings:
- Operation must have at least one `4XX` response.
- Info object should contain `license` field.
I created the following DOCSP tickets that will eventually turn these warnings back on:
- [(DOCSP-26643) [Admin API] Add info.license & re-enable lint rule](https://jira.mongodb.org/browse/DOCSP-26643)
- [(DOCSP-26644) [Admin API] 4XX Responses](https://jira.mongodb.org/browse/DOCSP-26644)
=> Add Redocly OpenAPI lint config

source/includes/kotlin-install-prerequisites.rst, source/includes/tutorial-template-prerequisite.rst, source/tutorial/backend.txt, source/tutorial/dotnet.txt, source/tutorial/flutter.txt, source/tutorial/kotlin.txt, source/tutorial/react-native.txt, source/tutorial/swiftui.txt
This PR adds more prerequisite info to the React Native Tutorial. The Swift tutorial had excellent relevant content for this, so I just pulled it over. ~~Long term, we should look at standardizing these prerequisite sections - potentially refactoring common bits like what's added here into an include that can be shared.~~
I abstracted the generic prerequisites to an include and updated the other tutorials with it.
- https://jira.mongodb.org/browse/DOCSP-26166
- [React Native Tutorial > Prerequisites](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26166/tutorial/react-native/#prerequisites)
- [Flutter Tutorial > Prerequisites](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26166/tutorial/flutter/#prerequisites)
- …
=> (DOCSP-26166) Copy prereq from SwiftUI tutorial to React Native tutorial

snooty.toml
Update Atlas Function max request timeout to 180s
- https://jira.mongodb.org/browse/DOCSP-26912
- [Atlas Functions > Constraints section](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26912/functions#constraints)
=> (DOCSP-26912): Update Atlas Function max request timeout to 180s

source/openapi-admin-v3.yaml
- (DOCSP-26317) [Admin API] Configure user session refresh token expiration
- [Admin API > Get/Set User Session Refresh Token Expiration](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/token-expiration/admin/api/v3/#tag/security/operation/adminGetRefreshTokenExpiration)
=> (DOCSP-26317) [Admin API] Configure user session refresh token expiration

source/data-api/custom-endpoints.txt
- https://jira.mongodb.org/browse/DOCSP-26974
- [Custom HTTPS Endpoints](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26974/data-api/custom-endpoints/#write-an-endpoint-function)
=> (DOCSP-26974): Add end-to-end example for a custom HTTPS endpoint function

source/users/enable-user-metadata.txt
This PR adds several SDK links  to the User Metadata page. It should be merged _after_ the new Node.js SDK page for [user meta data PR](https://github.com/mongodb/docs-realm/pull/2503) is merged.
- https://jira.mongodb.org/browse/DOCSP-27327
- [Enable User Metadata](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27372/users/enable-user-metadata/#access-user-metadata-from-a-client-application)
=> (DOCSP-27327) Update user metadata SDK links

source/data-api/custom-endpoints.txt, source/data-api/generated-endpoints.txt
- (DOCSP-27741) Bearer Auth Example for Custom & Generated Endpoints
- [Generated Endpoints > Authenticate the Request](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/api-auth/data-api/generated-endpoints/#authenticate-the-request)
- [Custom Endpoints > Authenticate the Request](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/api-auth/data-api/custom-endpoints/#authenticate-the-request)
=> (DOCSP-27741) Bearer Auth Example for Custom & Generated Endpoints

source/data-api/authenticate.txt, source/data-api/custom-endpoints.txt, source/data-api/generated-endpoints.txt, source/graphql/authenticate.txt, source/includes/bearer-auth-performance.rst, source/includes/dont-use-api-key-in-browsers.rst
- (DOCSP-27945) Bearer Auth: Client API Keys & Throughput
- [Generated Endpoints > Authenticate the Request](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/data-api/data-api/generated-endpoints/#authenticate-the-request)
- [Custom Endpoints > Authenticate the Request](custom-endpoints/#authenticate-the-request)
- [Authenticate Data API Requests](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/data-api/data-api/authenticate/)
- [Authenticate GraphQL Requests](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/data-api/graphql/authenticate/)
=> (DOCSP-27945) Bearer Auth: Client API Keys & Throughput

source/authentication/custom-function.txt
- Add link to Authenticate Users - Kotlin SDK page for new Custom Function authentication
- Replace tabbed, hardcoded examples with links to respective SDK docs
- https://jira.mongodb.org/browse/DOCSP-28243
- [Custom Function Authentication](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/docsp-28243-kotlin-custom-functions/authentication/custom-function/)
=> (DOCS-28243): Add Kotlin link to Custom Function Auth page

source/functions.txt
Adding link to new Kotlin Call a Function page
- https://jira.mongodb.org/browse/DOCSP-28233
- [Atlas Functions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/docsp-28233-kotlin-functions/functions/#call-from-realm-sdks)
=> (DOCSP-28233): Add Kotlin link to Functions page

source/includes/extracts-http-action.yaml, source/services/http-actions/http.post.txt
Add missing `encodeBodyAsJSON` parameter to http.post() page and specify it's required when payload is an object
- https://jira.mongodb.org/browse/DOCSP-27944
- [http.post()](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/docsp-27944/services/http-actions/http.post/#parameters)
=> DOCSP-27944): Add encodeBodyAsJSON parameter to http.post()

source/schemas.txt, source/sync/go-to-production/production-checklist.txt
- (DOCSP-28263) App Services Schema vs Built-In Schema Validation
- [Schemas > App Services Schema vs Built-In Schema Validation](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/schemas/schemas/#std-label-schema-app-services-vs-built-in)
- [Sync > Production Checklist](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/schemas/sync/go-to-production/production-checklist/)
=> (DOCSP-28263) App Services Schema vs Built-In Schema Validation

source/schemas.txt
[Feedback] Remove extra `the` in Schemas page 
- [Schemas](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/no-jira-schema-typo-fix/schemas/#what-is-a-schema-)
=> Fix reported typo in Schemas page

source/reference/metrics.txt
- (DOCSP-28388) Consistent GraphQL app metric naming
- [Reference > Metrics](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/graphql-metrics/reference/metrics/#available-metrics)
=> (DOCSP-28388) Consistent GraphQL app metric naming

source/authentication/custom-jwt.txt, source/includes/warn-terminate-sync-client-reset.rst, source/sync/app-builder/stream-data-from-client-to-atlas.txt, source/sync/app-builder/sync-data-in-atlas-with-client.txt, source/sync/app-builder/sync-data-in-client-with-atlas.txt, source/sync/configure/pause-or-terminate-sync.txt, source/sync/data-model/data-model-map.txt, source/sync/error-handling/client-resets.txt, source/sync/error-handling/errors.txt, source/sync/get-started.txt, source/users/create.txt, source/users/manage.txt
remove tabs with sdk links inside step directives. done b/c causes x-overflow issues per https://jira.mongodb.org/browse/DOP-3589
also removed all `.. tabs-realm-languages::` that just contain links to SDK pages, replacing them with a list of SDK links. this is something we've talked about doing in the past. figured i'd get it in while doing related work here.
n/a
- [App Services (changes throughout)](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/remove_long_tabs_in_steps/)
=> remove sdk realm language tabs

source/openapi-admin-v3.yaml
- (DOCSP-28584) [Admin API] Don't use function_name in endpoint request body
- [Admin API](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-function-name/admin/api/v3/)
=> (DOCSP-28584) [Admin API] Don't use function_name in endpoint request body

source/reference/partition-based-sync.txt, source/sync/go-to-production/optimize-sync-atlas-usage.txt
Split up the sync optimization page into flexible sync and partition sync. keep flexible sync content on current page, and move partition-based content to the partition based sync page in reference docs.
- https://jira.mongodb.org/browse/DOCSP-27737
- [Optimize Sync Atlas Usage](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27737/sync/go-to-production/optimize-sync-atlas-usage/)
- [Partition-Based Sync](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27737/reference/partition-based-sync/)
=> (DOCSP-27737): Split up the sync optimization page into flexible sync and partition sync

source/sync/configure/pause-or-terminate-sync.txt
No Jira 
- Add Flutter link to Re-Enable Sync section per [forum post](https://www.mongodb.com/community/forums/t/request-for-modifying-documentation-for-client-reset-logic-termination-of-sync/220200/2?u=dave_nielsen)
- Convert tabs to bullet list
- [Pause or Terminate Sync](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/no-jira-add-flutter-sync-link/sync/configure/pause-or-terminate-sync/#re-enable-sync)
=> Add Flutter link to Re-Enable Sync section

source/tutorial/swiftui.txt
- https://jira.mongodb.org/browse/DOCSP-29192
- [SwiftUI Tutorial](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-29192/tutorial/swiftui/)
=> (DOCSP-29192): SwiftUI Tutorial: Fix outdated realmApp naming

source/authentication/api-key.txt
- (DOCSP-29586) Add links to API Key docs to show how to create user API keys
- [API Key Authentication > Realm SDK Examples](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/api-key-sdk/authentication/api-key/#realm-sdk-examples)
=> (DOCSP-29586) Add links to API Key docs to show how to create user API keys

config/redirects
- https://jira.mongodb.org/browse/DOP-3584
###
Output once transmogrified with mut-redirects:
```
Redirect 301 /docs/atlas/app-servicesAtlas%20App%20Services https://www.mongodb.com/docs/atlas/app-services/
```
=> DOP-3584: add redirect for weird App Services-with-spaces URL

source/triggers/database-triggers.txt
- Note that most of what is being asked for in the ticket was already done elsewhere.
- I don't think we should recommend fullDocumentBeforeChange because it requires special cluster configuration.
- https://jira.mongodb.org/browse/DOCSP-28050
- [Database Triggers](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/match-clarity/triggers/database-triggers/#use-match-expressions-to-limit-trigger-invocations)
=> (DOCSP-28050): Clarify match expression

source/authentication/custom-jwt.txt, source/users/sessions.txt
- (DOCSP-29672) JWT exp does not control refresh token expiration
- [Authenticate & Manage Users > Manage User Sessions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/jwt-exp/users/sessions/)
- [Authenticate & Manage Users > Custom JWT Auth](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/jwt-exp/authentication/custom-jwt/)
=> (DOCSP-29672) JWT exp does not control refresh token expiration

openapi-data-api-v1/components/schemas/DeleteResponseBody.yaml, openapi-data-api-v1/components/schemas/InsertManyResponseBody.yaml, openapi-data-api-v1/components/schemas/InsertOneResponseBody.yaml, openapi-data-api-v1/components/schemas/UpdateResponseBody.yaml, source/openapi-data-api-v1.bundled.yaml
- Removes overspecified base types. allOf can extend but not override.
- This fixes some warnings that we were getting in the build log. Shouldn't actually affect the rendered output.
- [Data API OpenAPI Spec](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/openapi-fix/data-api/openapi/)
=> Remove unneeded OpenAPI types that cause warnings

examples/data-api/backend/data_sources/mongodb-atlas/default_rule.json, examples/data-api/backend/http_endpoints/data_api_config.json, examples/data-api/custom-endpoints.sh, examples/data-api/generated-endpoints.sh, examples/data-api/utils.sh, source/data-api/authenticate.txt, source/data-api/generated-endpoints.txt, source/data-api/snippets/generated-endpoints.snippet.auth-apiKey.sh, source/data-api/snippets/generated-endpoints.snippet.auth-bearer.sh, source/data-api/snippets/generated-endpoints.snippet.auth-emailPassword.sh, source/data-api/snippets/generated-endpoints.snippet.auth-jwtTokenString.sh
- (DOCSP-29278) Tested Endpoint Authentication Examples
- [Data API > Generated Endpoints > Authenticate the Request](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/data-api-auth/data-api/generated-endpoints/#std-label-data-api-authenticate)
- [Data API > Authenticate Data API Requests](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/data-api-auth/data-api/authenticate/)
=> (DOCSP-29278) Tested Endpoint Authentication Examples

source/authentication/custom-function.txt, source/sync/get-started.txt
Note for reviewer: I was initially going to update the naming from Alpha to Beta for the upcoming release, but we mostly omit the alpha/beta verbiage here in App Services, so I opted to remove it entirely, instead, for consistency and reduced maintenance overhead. In that case, there's no need to wait to merge this.
- https://jira.mongodb.org/browse/DOCSP-29752
- [Custom Function Authentication](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-29752/authentication/custom-function/)
- [Sync/Get Started](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-29752/sync/get-started/)
[REVIEWING.md](https://github.com/mongodb/docs-app-services/blob/mast …
=> (DOCSP-29752): C++: Omit Alpha naming references

source/sync/migrate-sync-modes.txt
The Java client SDK now supports backend Sync mode migration.
[Migrate Device Sync Modes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/sync-migration-java/sync/migrate-sync-modes/#requirements)
=> Backend Sync mode migration: Java SDK support

source/includes/important-stop-tiered-sync-server.rst, source/sync/app-builder/tiered-device-sync/index.txt
DO NOT MERGE until this release lands, currently scheduled for June 7.
- https://jira.mongodb.org/browse/DOCSP-30142
- [Tiered Device Sync Guide](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-30142/sync/app-builder/tiered-device-sync/index/#get-the-tiered-sync-server-code)
=> (DOCSP-30142): Tiered Device Sync: Use the 'latest' URL in distribution details

source/graphql.txt
- (DOCSP-29754) [GraphQL] Some schema title conflicts can be safely ignored
- [GraphQL API > Limitations](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/gql-titles/graphql/#limitations)
=> (DOCSP-29754) [GraphQL] Some schema title conflicts can be safely ignored

source/sync/migrate-sync-modes.txt
The React Native and Node.js SDKs now support backend Sync mode migration.
- [Migrate Device Sync Modes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/sync-migration-js/sync/migrate-sync-modes/#requirements)
=>  Backend Sync mode migration: Realm.js support 

source/tutorial/react-native.txt
Emphasized the correct line in code block in the React Native Template App tutorial... src/ItemListView.tsx, in the createItem() function: --> line 7 (“priority”) should be emphasized, rather than line 8 ( “});” )
- https://jira.mongodb.org/browse/DOCSP-30826
- [Device Sync Tutorial - React Native](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-30826/tutorial/react-native/)
=> (DOCSP-30826) Fix Emphasized Line in React Native Template App Tutorial

source/triggers/database-triggers.txt
On this page, in the example, I believe the line with the code referencing `await customers.findOne({_id: customer_id})` should be:
`await customers.findOne({_id: customerId })` 
- https://jira.mongodb.org/browse/DOCSP-30467
- [Database Triggers](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-30467/triggers/database-triggers/)
=> (DOCSP-34067) DB Trigger example has incorrect variable

source/functions.txt, source/reference/config/functions.txt
Update docs to note that App Services does not recognize functions in nested subdirectories when using automatic GitHub deployments until https://jira.mongodb.org/browse/BAAS-13185 is complete
- https://jira.mongodb.org/browse/DOCSP-31237
- [Functions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/docsp-31237-nested-fxn/functions/)
=> (DOCSP-31237): Warn users that nested functions are not allowed with auto GH deploy

source/security/private-endpoints.txt
- (DOCSP-31492) Private Endpoint Apps won’t connect over public internet
- [Use a VPC Private Endpoint (Preview)](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/private-endpoints/security/private-endpoints/)
=> (DOCSP-31492) Private Endpoint Apps won’t connect over public internet

source/apps/change-deployment-models.txt
For reference, the details came from [this thread](https://mongodb.slack.com/archives/CLY6HQWUE/p1688105109330279).
 
The SDKs that support the latest changing deployment models will need to be based on Realm Core 13.13.0 or later. This includes the following SDK versions (or later):
JS - pending v12.0.0 (not yet officially released, however 12.0.0-rc.0 was released on 2023-06-29 with support)
Swift - v10.40.0 (released 2023-05-26)
Kotlin - v1.10.0 (released 2023-06-28)
Java - v10.16.0 (released 2023-06-02)
Flutter/Dart - v1.2.0 (released 2023-06-08)
Dotnet - 11.1.0 (released on 2023-06-17)
CPP - 0.2.0 Preview (released 2023-06-21)
- https://jira.mongodb.org/browse/DOCSP-31122
- [Change Deployment Modes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-3112 …
=> (DOCSP-31122) list minimum supported SDK versions needed for deployment model change

source/sync/migrate-sync-modes.txt
- https://jira.mongodb.org/browse/DOCSP-31743
- [Migrate Device Sync Modes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-31743/sync/migrate-sync-modes/#migrate-client-app-to-flexible-sync): Update links in "Migrate Client App to Flexible Sync" section from FS subscription management to new dedicated destination
=> Add links to new SDK docs on migrating Sync modes

source/reference/config/template-expansions.txt
- (DOCSP-31570) Template config expansions only support string values
- [Create Template Configurations with Expansions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/template-expansions/reference/config/template-expansions/)
=> (DOCSP-31570) Template config expansions only support string values

source/users/custom-metadata.txt
Update corresponding App Services page with link to User Metadata - Kotlin SDK page added in https://github.com/mongodb/docs-realm/pull/2944
- https://jira.mongodb.org/browse/DOCSP-32114
- [Define Custom User Metadata](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/docsp-32114-kotlin-user-metadata/users/custom-metadata/#access-user-metadata-from-a-client-application)
=> DOCSP-32114: Add Kotlin link to Define User Metadata page

source/includes/define-custom-user-data.rst
- https://jira.mongodb.org/browse/DOCSP-30623
- [Device Sync Permissions Guide note at bottom of each "Enable & Configure Custom User Data" sections](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-30623/sync/app-builder/device-sync-permissions-guide/#enable---configure-custom-user-data-1)
=> DOCSP-30623 Restart sync after updating custom user data

source/users/custom-metadata.txt
https://jira.mongodb.org/browse/DOCSP-31506
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/custom_user_data/users/custom-metadata/#specify-the-user-id-field
=> User ID can now be type ObjectID or string

source/functions/mongodb/write.txt
Bug bash ticket: [Write](https://www.mongodb.com/docs/atlas/app-services/functions/mongodb/write/#update) page is missing `findOneAnd...()` methods. 
> NOTE: I didn't include code examples since they're available on the linked [API Ref](https://www.mongodb.com/docs/atlas/app-services/functions/mongodb/api/#collection.findoneandupdate--) page. I can also update to make these their own sections if we think that's needed.
- https://jira.mongodb.org/browse/DOCSP-31445
- [Write](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/BRANCH_NAME/)
=> DOCSP-31445: Add links to findOneAnd...() methods

source/openapi-admin-v3.yaml, source/reference/config/graphql.txt
- (DOCSP-32691) [BAAS] Support disabling graphql introspection in the backend
- [Reference > Config > GraphQL](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/introspection/reference/config/graphql/)
- [Admin API > GraphQL Config Endpoints](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/introspection/admin/api/v3/#operation/adminGetGraphQLConfig)
=> (DOCSP-32691) [BAAS] Support disabling graphql introspection in the backend

source/openapi-admin-v3.yaml
https://jira.mongodb.org/browse/DOCSP-32131
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/master/admin/api/v3/#tag/functions/operation/adminCreateFunction
The purpose of ths ticket is to update the Admin API's NewFunction properties to include the two missing ones from https://www.mongodb.com/docs/atlas/app-services/reference/config/http_endpoints/#data-api-configuration. The property names and descriptions copied from that source.
=> add missing properties to NewFunction

source/sync/configure/enable-sync.txt, source/sync/configure/sync-settings.txt, source/sync/error-handling/errors.txt, source/sync/go-to-production/optimize-sync-atlas-usage.txt
This functionality is pending release, and should not be merged until the App Services release currently targeted for Sept 4.
Before merging:
I split out a separate ticket to update the Admin API Sync endpoint as it is currently missing FS info entirely.
The corresponding [SDK docs PR is 2977](https://github.com/mongodb/docs-realm/pull/2977).
- https://jira.mongodb.org/browse/DOCSP-31839
- [Sync Settings/Queryable Fields](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-31839/sync/configure/sync-settings/#queryable-fields)
- [Sync Errors](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-31839/sync/error-handling/errors/#flexible-sync-errors) …
=> (DOCSP-31839): Update queryable fields for upcoming release

source/sync/app-builder/stream-data-from-client-to-atlas.txt, source/sync/configure/sync-settings.txt
- https://jira.mongodb.org/browse/DOCS-16377
- [Stream Data from Client to Atlas](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCS-16377/sync/app-builder/stream-data-from-client-to-atlas/#create-asymmetric-objects-and-write-data)
- [Configure Sync - Data Ingest](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCS-16377/sync/configure/sync-settings/#data-ingest)
=> (DOCS-16377): Data ingest does not leave objects in realms on device

source/reference/service-limitations.txt
https://jira.mongodb.org/browse/DOCSP-33232
https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/docsp-33232/reference/service-limitations/#connection-pooling
=> Add connection pooling information

source/apps/metadata.txt
- (DOCSP-33503) Unhide Find Your App ID CLI procedure
- [Apps > Metadata](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/unhide/apps/metadata/)
=> (DOCSP-33503) Unhide Find Your App ID CLI procedure

source/edge-server/configure.txt
- https://jira.mongodb.org/browse/DOCSP-33859
- [Configure Edge Server](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-33859/edge-server/configure/#required-network-access)
=> (DOCSP-33859): Edge Server: Add required networking details

source/triggers.txt, source/triggers/database-triggers.txt
- (DOCSP-34109) Trigger Throughput Wording
- [Triggers](https://preview-mongodbnlarew.gatsbyjs.io/atlas-app-services/throughput/triggers/)
- [Database Triggers](https://preview-mongodbnlarew.gatsbyjs.io/atlas-app-services/throughput/triggers/database-triggers/)
=> (DOCSP-34109) Trigger Throughput Wording

source/apps/copy.txt, source/apps/create.txt, source/tutorial/dotnet.txt, source/tutorial/flutter.txt, source/tutorial/kotlin.txt, source/tutorial/react-native.txt, source/tutorial/swiftui.txt
This PR: 
- Removes the `--location` flag from the template app documentation examples
- Replaces the flag with the new `--provider-region` in the appservices-cli documentation 
- Leaves the `--location` flag in the deprecated realm-cli documentation
- https://jira.mongodb.org/browse/DOCSP-34580
- Get Started:
- [.NET Tutorial](https://preview-mongodbcbullinger.gatsbyjs.io/atlas-app-services/docsp-34580/tutorial/dotnet/#start-with-the-template)
- [Flutter Tutorial](https://preview-mongodbcbullinger.gatsbyjs.io/atlas-app-services/docsp-34580/tutorial/flutter/#start-with-the-template)
- [Kotlin Tutorial](https://preview-mongodbcbullinger.gatsbyjs.io/atlas-app-services/docsp-34580/tutorial/kotlin/#start-with-the-template)
- [RN Tutorial](https://preview-mongodbcbullinger.gatsbyjs.io/atlas-app …
=> DOCSP-34580: Update --location flag in template app documentation

source/includes/note-partition-relationships.rst, source/logs/sync.txt, source/reference/partition-based-sync.txt, source/reference/service-limitations.txt, source/rules/roles.txt, source/rules/sync-compatibility.txt, source/schemas/relationships.txt, source/sync/configure/enable-sync.txt, source/sync/configure/pause-or-terminate-sync.txt, source/sync/configure/sync-settings.txt, source/sync/error-handling/errors.txt, source/sync/get-started.txt, source/sync/go-to-production/optimize-sync-atlas-usage.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-34418
- [Partition-Based Sync Mode](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-34418/reference/partition-based-sync/#partition-strategies)
- [Sync Settings](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-34418/sync/configure/sync-settings/)
Other
- Pages throughout the docs set: Partition-Based Sync (PBS) has been removed from the App services UI. As a result, removed mentions of PBS throughout the docs and moved relevant PBS content to the Partition-Based Sync Mode reference page.
=> DOCSP-33418 Remove PBS mentions form the docs

source/edge-server/connect.txt, source/edge-server/mongodb.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-34585
- [Connect to an Edge Server](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-34585/edge-server/connect/): Move the "connect" section from the Use MongoDB APIs with Edge Server page so all the connection info is together. Add details about the different ways you can connect - via Device SDK or the MongoDB connection URI.
- [Use MongoDB APIs with Edge Server](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-34585/edge-server/mongodb/): Remove the "Connect" section, add a link to its new location on the "Connect" page.
- Connect to Edge Server: Move the "connect" section from the "Use MongoDB APIs with …
=> (DOCSP-34585): Clarify details about the different ways of connecting with Edge Server

source/openapi-admin-v3.yaml
Jira tickets: 
- https://jira.mongodb.org/browse/DOCSP-34712
- https://jira.mongodb.org/browse/DOCSP-34724
- https://jira.mongodb.org/browse/DOCSP-34675
- https://jira.mongodb.org/browse/DOCSP-34710
- [Admin API - List Schemas](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-34712/admin/api/v3/#tag/schemas/operation/adminListSchemas): Remove the `schema` object that does not match the actual API implementation.
- [Admin API - Create a Schema](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-34712/admin/api/v3/#tag/schemas/operation/adminCreateSchema): Add details about JSON escaping to avoid errors when creating a schema.
- [Admin API - Create a Deployment Draft](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-34 …
=> (DOCSP-34712): Admin API/List Schemas: Remove schema object to match API implementation

source/sync/configure/sync-settings.txt, source/sync/error-handling/errors.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-33212
- [Sync Settings](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-33212/sync/configure/sync-settings/#indexed-queryable-fields): Note that attempting to change an indexed queryable field value on device causes a compensating write error. Link to the compensating write error documentation for more information.
- [Sync Errors](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-33212/sync/error-handling/errors/#flexible-sync-errors): Add attempting to change an indexed queryable field value to the list of conditions that can trigger a compensating write error.
- Configure Sync/Sync Settings: Note that …
=> (DOCSP-33212): Updating an IQF value from device causes a compensating write

source/authentication/custom-jwt.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-34600
- [Custom JWT Authentication](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-34600/authentication/custom-jwt/)
- Authenticate and Manage Users/Authentication Providers/Custom JWT: Note that App services specifies a 30 minute expiry for the access token even if expiry is defined by the Custom JWT's ``exp`` key. 
=> DOCSP-34600 Mention that exp field is ignored for custom JWT

source/release-notes/backend.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-34996
- [Release Notes > 13 December 2023 Release](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-34996/release-notes/backend/#13-december-2023-release)
=> DOCSP-34996 External release notes for v20231213

source/functions.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35176
- [Atlas Functions](https://preview-mongodbcbullinger.gatsbyjs.io/atlas-app-services/docsp-35176-nested-functions/functions/#define-a-function): Update step 2 (for UI and CLI) in Define a Function procedure to remove caveat about nested functions not supported when using GitHub deployment
- genre
- **Functions**: Update the Define a Function procedure to no longer specify nested functions are unsupported when using GitHub deployment.
=> DOCSP-35176: Remove caveat about nested functions with GH deployment

source/sync/data-model/data-model-map.txt, source/sync/error-handling/client-resets.txt
- [Data Model Mapping/Sets](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/cpp-ga-link-updates/sync/data-model/data-model-map/#sets): Add C++ SDK's new Set data type to the list.
- [Client Reset](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/cpp-ga-link-updates/sync/error-handling/client-resets/): Add C++ client reset documentation to the list. Start list items with SDK name to make it easier for users to quickly identify the correct link.
- genre
- Configure & Update Your Data Model/Data Model Mapping: Add C++ Set to the list of SDK Set documentation links.
- Handle Errors/Client Reset: Add the new C++ Client Reset page to …
=> Add links to new C++ GA content

source/includes/app-services-cli-overview.rst
- [CLI Profiles](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/macos-cli-profile-path/cli/#cli-profiles)
- genre
- **CLI Profiles**
- Updated the profile configuration file path to be nested under `$HOME` on macOS
=> Fix CLI profile config path for macOS

source/rules.txt, source/rules/filters.txt, source/rules/roles.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35902
- [Role-based Permissions](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-35902/rules/roles/#define-roles---permissions): note at bottom of page about security considerations
- [Filter Incoming Queries](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-35902/rules/filters/#procedure): note at bottom of page about security considerations
- genre
- Define Data Access Permissions
- Role-based Permissions: Add note about security consideration for roles and filters for queries. 
- Filter Incoming Queries: Add note about security consideration for roles and filters for …
=> DOCSP-35902 Security considerations for roles and query filtering

source/includes/important-sync-ignores-custom-collation.rst, source/rules/sync-compatibility.txt, source/sync/get-started.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-36140
We don't have a great place to add this information. I've added it to a couple of spots where it may be relevant, but I'm open to other suggestions. I'm also on the fence about whether we should include this information in the SDKs, too.
- [Get Started](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-36140/sync/get-started/#create-queries-in-your-client-application): Add new include to the "Create queries in your client application" section.
- [Device Sync-Compatible Permissions](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-36140/rules/sync-compatibility/): Add new include to the intro.
- genre …
=> (DOCSP-36150): Add callout about ignoring collation

source/openapi-admin-v3.yaml
Current OpenAPI spec doesn't account for `mongodb-cloud` as it should according to documentation in [Get an Admin API Session Access Token](https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#section/Get-an-Admin-API-Session-Access-Token)
The example specifies `mongodb-cloud` as the provider but it's not included in `ProviderType` in the spec file.
Example: https:// services.cloud.mongodb.com/api/admin/v3.0/auth/providers/`mongodb-cloud`/login
~~This PR adds the necessary provider so generated clients can access the Atlas App Services Admin API.~~
This PR hardcodes the provider into the path and removes the need for parameters.
- **Update adminLogin operation**
- /auth/providers/mongodb-cloud/login …
=> Update OpenAPI adminLogin endpoint

source/cli/appservices-logs-list.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-36194
- [appservices logs list](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-36194/cli/appservices-logs-list/#options): Added ``trigger_error_handler`` as value for the ``--type`` flag in the Options table. 
- genre
**Reference**
- App Services CLI/logs/list: Add``trigger_error_handler`` as value for the ``--type`` flag in the Options table. 
=> DOCSP-36194 Update CLI logs list with trigger_error_handler type

source/openapi-admin-v3.yaml
Swift Open API generator errors out on the ServiceResponse properties because they aren't parsable.
This PR fixes the syntax of ServiceResponse properties.
- **Update ServiceResponse**
- Fixed syntax of object properties
=> Fix OpenAPI ServiceResponse schema

source/users/sessions.txt
- [Manage User Sessions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/sessions-url/users/sessions/)
- Fix the base URL to not include auth provider information (specified in the next step)
- Tweak placeholder spacing to be consistent
- Convert tab to space for correct spacing on some curl request examples
- genre
=> Correct Base URL, spacing tweaks

.github/workflows/check-openapi-admin-v3.yml
This will run the OpenAPI linter on changes to the Admin API spec. This will let us block PRs that introduce errors.
=> GitHub action to lint Admin API spec

source/openapi-admin-v3.yaml
Jira ticket: https://jira.mongodb.org/browse/DOCSP-36901
- [App Services Admin API](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-36901/admin/api/v3/#tag/deploy/operation/adminRedeployDeployment): Correct `/redeploy` operation type from `Get` to `Post`.
- genre
- **App Services Admin API**
- Correct `/redeploy` operation type from `Get` to `Post`.
=> (DOCSP-36901): Fix incorrect operation for redeploy

source/sync/error-handling/errors.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-33924
- [Sync Errors](https://preview-mongodbcbullinger.gatsbyjs.io/atlas-app-services/docsp-33924-maxIntegrationAttempts/sync/error-handling/errors/#mongodb-translator-errors): Add `MaxIntegrationAttempts` error to MongoDB Translator Errors section table.
- genre
- Handle Errors > Sync Errors: Update MongoDB Translator Errors section table to include 'MaxIntegrationAttempts' error description and typical resolution.
=> DOCSP-33924: Add MaxIntegrationAttempts to Sync Errors page

source/includes/x509-encryption.rst, source/mongodb.txt, source/security/network.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35929
- [Configure Network Security](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-35929/security/network/#transport-layer-security--tls-): Moved note about x509 security certificate between Atlas App Services and Atlas data sources to a more appropriate spot higher up on the page.
- [Connect to MongoDB Data Sources](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-35929/mongodb/): Added note about x509 security certificate between Atlas App Services and Atlas data sources.
- genre
**Connect to a MongoDB Data Sources**
- Landing Page: Added note about x509 security …
=> DOCSP-35929 Move x509 security note to more appropriate spot

source/authentication/custom-jwt.txt, source/release-notes/backend.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-37744
- [Custom JWT Authentication](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-37744/authentication/custom-jwt/#metadata-fields): Increase token character limit from 2048 to 4096.
- genre
- **Authenticate & Manage Users**
- Authentication Providers/Custom JWT: Increase token character limit from 2048 to 4096.
=> (DOCSP-37744): Increase JWT token character limit to 4096

source/authentication/custom-jwt.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-37744
- [Custom JWT Authentication](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-37744-2/authentication/custom-jwt/#metadata-fields): Clarify wording about JWT length and the 4096 character limit being _per_ metadata field.
- genre
Omitting release notes here since it's really just iteration on the prior PR. Same work, just refinements.
=> (DOCSP-37744): Add JWT limit and clarify metadata field limit

source/domain-migration.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-38798
- [Domain Migration](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-38798/domain-migration/): Add SDK versions that use the new baseURL by default.
- genre
- **Other**
- Domain Migration: Add SDK versions that use the new baseURL by default.
=> (DOCSP-038798): Domain Migration: Add SDK versions that use the new baseURL by default

source/apps/deployment-models-and-regions.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-38678
- [Deployment Models & Regions](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-38678/apps/deployment-models-and-regions/): Correct GCP deployment region "Ohio" to "Iowa" per engineering updates. Remove AWS-style abbreviations.
DO NOT MERGE until this week's BAAS release.
- genre
- **Develop & Deploy Apps**
- Deployment Models & Regions: Correct GCP deployment region "Ohio" to "Iowa" per engineering updates. Remove AWS-style abbreviations.
=> (DOCSP-38678): Fix deployment labels for GCP

config/redirects, source/index.txt, source/tutorial/backend.txt, source/tutorial/dotnet.txt, source/tutorial/flutter.txt, source/tutorial/kotlin.txt, source/tutorial/react-native.txt, source/tutorial/swiftui.txt, source/tutorial/triggers-fts.txt, source/tutorials.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-38548
- [Home page](https://preview-mongodbkrollinsmdb.gatsbyjs.io/atlas-app-services/DOCSP-38548/):
- Changed "Get Started" TOC entry to "Tutorials"
- Flipped the TOC construction for tutorial pages from "Device Sync Tutorial - <LANGUAGE>" to "<LANGUAGE> - Device Sync"
- Individual tutorial pages:
- Updated page titles to clearly indicate they're tutorials and include product names
- Added meta descriptions and keywords to those that didn't have them 
- genre
- **Tutorials**
- Changed "Get Started" TOC entry to "Tutorials"
- Flipped the TOC construction for tutorial pages from "Device Sync Tutorial - <LANGUAGE>" to …
=> (DOCSP-38548) Standardize tutorial page names

source/mongodb/crud-and-aggregation-apis.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-38453
- [CRUD & Aggregation APIs](https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/DOCSP-38453/mongodb/crud-and-aggregation-apis/#aggregation-pipeline-operator-availability): Added `$setIsSubset`. Did not add `distinct` because it is a command, and we [explicitly state commands are not supported](https://www.mongodb.com/docs/atlas/app-services/mongodb/crud-and-aggregation-apis/#database-commands) (with some exceptions). 
- genre
- Add $setisSubset to list of unsupported pipeline operators
=> added $setIsSubset as unsupported.

source/sync/configure/enable-sync.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-37913
- [Enable Atlas Device Sync](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-37913/sync/configure/enable-sync/#select-a-cluster-to-sync): For Admin API, added info on enabling development mode and edited steps for clarity. 
- genre
**Device Sync**
- Configure Sync/Enable Atlas Device Sync: For Admin API, added a step on enabling development mode and clarified procedure steps for updating and enabling sync.
=> DOCSP-37913 Enable development mode from API in Enable Sync Procedure

source/sync/details/conflict-resolution.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-38601
- [Conflict Resolution](https://preview-mongodbcbullinger.gatsbyjs.io/atlas-app-services/docsp-38601-dict-conflict-resolution/sync/details/conflict-resolution/#dictionaries): Add new "Dictionaries" section to clarify how Sync handles conflicts with dictionary key updates
- genre
- Technical Details/Conflict Resolution: Add new "Dictionaries" section to clarify how Device Sync handles conflicts with dictionary keys.
=> DOCSP-38601: Update Conflict Resolution with info on dictionary keys

source/includes/note-collections-in-mixed-sync.rst
Jira ticket: none
Update note to use `May 28, 2024`
- [Data Model Mapping](https://preview-mongodbcbullinger.gatsbyjs.io/atlas-app-services/no-jira-fix-date/sync/data-model/data-model-map/#collections-in-mixed-properties)
- **Device Sync**: 
- Configure and Update Your Data Model > Data Model Mapping: Update note for `Mixed Properties` to specify Collections in Mixed feature is only valid for App Services Apps created after `May 28, 2024`. 
- Define a Data Model > Schemas > Schema Data Types: Update note for `Mixed` data type to specify Collections in Mixed feature is only valid for App Services Apps created after `May 28, 2024`.  
=> Update date in coll in mixed note

source/authentication/email-password.txt, source/functions/mongodb/read.txt, source/openapi-admin-v3.yaml, source/reference/config/auth.txt, source/reference/config/v20210101/auth.txt, source/tutorial/cpp.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-40409
- [Atlas App Services Email/Password Authentication](https://preview-mongodbosharafmdb.gatsbyjs.io/atlas-app-services/DOCSP-40409-the-the-correction/authentication/email-password/): changed "the the" to "the" and added meta data
- [Query MongoDB Atlas Read](https://preview-mongodbosharafmdb.gatsbyjs.io/atlas-app-services/DOCSP-40409-the-the-correction/functions/mongodb/read/): changed "the the" to "the" and added meta data
- [Users & Authentication Providers](https://preview-mongodbosharafmdb.gatsbyjs.io/atlas-app-services/DOCSP-40409-the-the-correction/reference/config/auth/): changed "the the" to "the" and added meta data
- [Users & Authentication Providers v20210101](https://preview-mongodbosharafmdb.gatsbyjs.io/atlas-app-services …
=> DOCSP-40409 fixed the the error in app services docs

source/includes/note-collections-in-mixed-sync.rst, source/sync/data-model/data-model-map.txt
Quick fix: 
Correct version number for Collections in Mixed feature release (should be `10.51.0` instead of `10.15.0`)
- [Data Model Mapping](https://preview-mongodbcbullinger.gatsbyjs.io/atlas-app-services/no-jira-fix-version-number/sync/data-model/data-model-map/#collections-in-mixed-properties)
**Device Sync**
- Configure and Update Your Data Model > Data Model Mapping: Correct the minimum Swift SDK version number listed in the Collections in Mixed note.
=> Fix incorrect Swift version number for coll-in-mixed feature

source/data-api/custom-endpoints.txt, source/data-api/generated-endpoints.txt, source/security/private-endpoints.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-41041
- [Use a VPC Private Endpoint (Preview)](https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/DOCSP-41041/security/private-endpoints/#migrate-a-legacy-endpoint): Remove guidance on migrating to http endpoints and data api
- [Custom HTTPS Endpoints](https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/DOCSP-41041/data-api/custom-endpoints/#std-label-custom-endpoints): add note.
- [Data API Endpoints](https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/DOCSP-41041/data-api/generated-endpoints/#std-label-data-api-endpoints): add note.
- **Private Endpoints**
- Private endpoints do not support HTTPS Endpoints or the Data API.
=> Remove guidance on migrating to http endpoints and data api

source/includes/note-windows-zip.rst, source/tutorial/dotnet.txt, source/tutorial/flutter.txt, source/tutorial/kotlin.txt, source/tutorial/react-native.txt, source/tutorial/swiftui.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-36897
- [.Net Tutorial](https://deploy-preview-794--app-services.netlify.app/tutorial/dotnet/): Add note
- [Flutter Tutorial](https://deploy-preview-794--app-services.netlify.app/tutorial/flutter/): Add note
- [Kotlin Tutorial](https://deploy-preview-794--app-services.netlify.app/tutorial/kotlin/): Add note
- [React Native Tutorial](https://deploy-preview-794--app-services.netlify.app/tutorial/react-native/): Add note
- [Swift Tutorial](https://deploy-preview-794--app-services.netlify.app/tutorial/swiftui/): Add note
- **Downloaded ZIP might not open in Windows**
- When downloading the .zip file for a tutorial from the UI, the default Windows zip utility might not work. Use a third-party tool to unzip the file.
=> add note about UI-downloaded zip not working (always) on windows

source/sync/app-builder/device-sync-permissions-guide.txt
Jira ticket: https://jira.mongodb.org/browse/DOCS-16807
- [Device Sync Permissions Guide](https://preview-mongodbosharafmdb.gatsbyjs.io/atlas-app-services/DOCSP-16807-typo-create-subscribetouser/sync/app-builder/device-sync-permissions-guide/#create-subscribetouser-function): fixed a typo and added metadata
- genre
- [N/A] Create a Jira ticket for related docs-realm work, if any
- App Builder's Resources/Device Sync Permissions Guide: Fix a typo under "Create subscribeToUser Function" and add metadata to the page.
=> DOCS-16807 fixed typo and added metadata

.github/pull_request_template.md, .github/workflows/add-netlify-links.yml
Adds github action to generate preview links in PR description. Updated the template to provide a placeholder for regex to match again (and know where to insert links).
This Action does **not** build links for files in /source/examples, /source/includes, or /source/images.
- If there is an include, provide links to pages that contain that include
- same with an image
- No pages to preview
=> Adds github action to generate preview links in PR description

source/users/custom-metadata.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-35175
- [Define Custom User Metadata](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-35175/users/custom-metadata/#modify-user-permissions-in-custom-user-data-documents): Add new section on editing permissions in custom user data documents
- genre
Authenticate and Manage Users
- Define User Metadata: Create a new section on updating permissions using custom user data.
=> DOCSP-35175 Refresh permissions when custom user data changes

.github/workflows/add-netlify-links.yml
Updates the netlify action so it doesn't append new links to the bottom of the PR description with each new push. 
TODO: 
- Move into single workflow, if possible (currently failing with "no content supplied")
Jira ticket: n/a
- **Update Netlify Link Action**
- Action no longer appends new links to the bottom of the PR description.
No pages to previewNo pages to preview
=> update action wip

source/tutorial/kotlin.txt, source/tutorial/react-native.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-37204
<li><a href=https://deploy-preview-830--app-services.netlify.app/tutorial/kotlin>tutorial/kotlin</a></li><li><a href=https://deploy-preview-830--app-services.netlify.app/tutorial/react-native>tutorial/react-native</a></li>
- genre
- **Tutorials**
- Kotlin & React Native: Remove `frontend` from instructions about finding the client code, as the path no longer includes a `frontend` directory.
=> (DOCSP-37204): Remove 'frontend' from template app tutorial instructions

source/cli/appservices-logs-list.txt, source/cli/appservices-pull.txt, source/cli/appservices-push.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-42889
<li><a href=https://deploy-preview-834--app-services.netlify.app/cli/appservices-logs-list>cli/appservices-logs-list</a></li><li><a href=https://deploy-preview-834--app-services.netlify.app/cli/appservices-pull>cli/appservices-pull</a></li><li><a href=https://deploy-preview-834--app-services.netlify.app/cli/appservices-push>cli/appservices-push</a></li>
- genre
- Reference
- App Services CLI: Update cli references for v2.0.0. Includes deprecation notes on the following flags for commands affected by GraphQL and Static Hosting deprecation:
- `logs list`: `--type`
- `pull`: `-s, --include-hosting`
- `push`: `-s, …
=> DOCSP-42889 CLI v2.0.0 updates w/ GraphQL deprecation

source/graphql.txt, source/graphql/migrate-neurelo.txt, source/migrate-hosting-graphql.txt
This PR adds info about migrating GraphQL services to Neurelo.
<li><a href=https://deploy-preview-839--app-services.netlify.app/graphql/migrate-neurelo>graphql/migrate-neurelo</a></li><li><a href=https://deploy-preview-839--app-services.netlify.app/graphql>graphql</a></li><li><a href=https://deploy-preview-839--app-services.netlify.app/migrate-hosting-graphql>migrate-hosting-graphql</a></li>
=> Add Neurelo as GraphQL migration option

source/functions/mongodb/api/snippets/transactions.js, source/functions/mongodb/write.txt
Removing any mentions + code of creating a configuration object that sets user's preferred read/write settings and passing it to the session method. These settings are not configured in this context and not respected.
Jira ticket: https://jira.mongodb.org/browse/DOCSP-42573
</li><li><a href=https://deploy-preview-860--app-services.netlify.app/functions/mongodb/write>functions/mongodb/write</a></li>
- genre
=> (DOCSP-42573) Update transactions in Functions info about read/write settings

source/triggers/database-triggers.txt
Our [Triggers docs](https://www.mongodb.com/docs/atlas/app-services/triggers/database-triggers/) have the following note about database triggers:
"Your app opens a single change stream for each collection with at least one enabled trigger. If multiple triggers are enabled for a collection they all share the same change stream."
This is not correct. We actually go in almost the opposite direction. We open a single changestream per database trigger. I am concerned it is leading some misunderstandings of the load that Triggers can put on a customer's cluster(s)
Jira ticket: https://jira.mongodb.org/browse/DOCSP-43465
<li><a href=https://deploy-preview-861--app-services.netlify.app/triggers/database-triggers>triggers/database-triggers</a></li>
Before merging your PR, make sure to check a few …
=> (DOCSP-43465) Incorrect information about Trigger changestream behavior in relation to Atlas clusters

source/openapi-admin-v3.yaml
Jira ticket: https://jira.mongodb.org/browse/DOCSP-44132
Staging links are not available for the App Services Admin API.
- genre
=> (DOCSP-44132): Admin API: Triggers & Endpoints - provide info on getting the service ID

source/openapi-admin-v3.yaml, source/reference/config/triggers.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-37062
Note for reviewer: it's not currently possible to view a staged version of the Admin API reference. I'll check it after deploy and fast follow to fix any errors.
<li><a href=https://deploy-preview-864--app-services.netlify.app/openapi-admin-v3.yaml>openapi-admin-v3.yaml</a></li><li><a href=https://deploy-preview-864--app-services.netlify.app/reference/config/triggers>reference/config/triggers</a></li>
- genre
=> (DOCSP-37062): Update Trigger config & Admin API details

source/data-api.txt, source/data-api/custom-endpoints.txt, source/data-api/generated-endpoints.txt, source/includes/note-third-party-services-deprecation.rst, source/index.txt, source/sync.txt
Update third-party service deprecation date to match HTTPS Endpoints deprecation date. Also, add some deprecation labels to top-level pages to help make it clearer at a glance what is deprecated.
Jira ticket: https://jira.mongodb.org/browse/DOCSP-44484
<li><a href=https://deploy-preview-867--app-services.netlify.app/data-api>data-api</a></li><li><a href=https://deploy-preview-867--app-services.netlify.app/data-api/custom-endpoints>data-api/custom-endpoints</a></li><li><a href=https://deploy-preview-867--app-services.netlify.app/data-api/generated-endpoints>data-api/generated-endpoints</a></li><li><a href=https://deploy-preview-867--app-services.netlify.app/index>index</a></li><li><a href=https://deploy-preview-867--app-services.netlify.app/sync>sync</a></li>
- [Third-party …
=> (DOCSP-44484) Update 3rd party service deprecation date

snooty.toml
Jira ticket: https://jira.mongodb.org/browse/DOCSP-44691
No pages to preview
=> (DOCSP-44691) Move triggers banner and remove last sentence

source/deprecation.txt, source/graphql/migrate-apollo.txt, source/graphql/migrate-hasura.txt, source/graphql/migrate-wundergraph.txt, source/hosting/migrate-blob.txt, source/hosting/migrate-netlify.txt, source/hosting/migrate-vercel.txt, source/migrate-hosting-graphql.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-46649
Update EOL date listed for GraphQL and Static Hosting from `March 12, 2025` to the extended date of `September 30, 2025`.
See https://github.com/10gen/baas-ui/pull/4795 for corresponding UI update.
=> DOCSP-46649: Update EOL date for GraphQL and Static Hosting

snooty.toml, source/data-api/data-api-deprecation.txt, source/data-api/migration/data-api-tutorial.txt, source/sync/migration/reactnativetutorial.txt
Jira ticket: https://jira.mongodb.org/browse/DOCSP-47132
Added new page for Data API alternative. Add link to new page on existing Data API Deprecation page 
<li><a href=https://deploy-preview-878--docs-app-services.netlify.app/data-api/migration/data-api-tutorial>data-api/migration/data-api-tutorial</a></li><li><a href=https://deploy-preview-878--docs-app-services.netlify.app/data-api/data-api-deprecation>data-api/data-api-deprecation</a></li><li><a href=https://deploy-preview-878--docs-app-services.netlify.app/sync/migration/reactnativetutorial>sync/migration/reactnativetutorial</a></li>
- genre
[REVIEWING.md](https://github.com/mongodb/docs-app-services/blob/master/REVIEWIN …
=> DOCSP-47132: Add new page for Data API alternative

source/data-api/migration/data-api-tutorial.txt
No Jira ticket; reported via Slack 
- Correct and clarify that the API key/secret used is only a locally defined key for basic auth, and is not an Atlas API key
- Fix broken link to node.js docs
=> Data API migration guide: Clarify API key and fix broken Node.js link

source/data-api/data-api-deprecation.txt, source/deprecation.txt
Add Eden as listed partner solution for data api migration
- [Data API and HTTPS Endpoints Deprecation](https://deploy-preview-883--docs-app-services.netlify.app/data-api/data-api-deprecation/#eden) page
Jira ticket: https://jira.mongodb.org/browse/DOCSP-49656
=> DOCSP-49656: Add Eden to Data API Deprecation page
