mongodb/docs-app-services

source/manage-apps/deploy/manual/rollback-deployment.txt

- (DOCSP-22577): Rollbacks do not redeploy hosted files
- [Roll Back Deployments](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/serverless/manage-apps/deploy/manual/rollback-deployment/)

(DOCSP-22577): Rollbacks do not redeploy hosted files

---

source/authentication/api-key.txt

- https://jira.mongodb.org/browse/DOCSP-22625
- [API Key Authentication](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-22625/authentication/api-key/)

(DOCSP-22625): Add Server API Key limit

---

source/manage-apps/configure/config/sync.txt
source/manage-apps/configure/config/triggers.txt
source/mongodb.txt
source/mongodb/limitations-data-lakes.rst
source/mongodb/limitations-serverless-instances.rst
source/reference/service-limitations.txt
source/sync/data-model/create-a-schema.txt
source/sync/learn/overview.txt
source/triggers/database-triggers.txt

- (DOCSP-22258): Service LImitations for Serverless & Data Lake
- (DOCSP-22259): Add Serverless to Link a Data Source
- (DOCSP-22260): Serverless Instance Configuration
- (DOCSP-22261): No change streams for data lake or serverless
- [MongoDB Data Sources](https://docs-mongodbcom-staging.corp.mongodb.com/app-services/docsworker-xlarge/serverless/mongodb/)

Limited Atlas Serverless Support

---

source/includes/create-auth-trigger.rst
source/includes/define-custom-user-data.rst
source/sync/data-access-patterns/flexible-sync-permissions-guide.txt

- https://jira.mongodb.org/browse/DOCSP-NNNNN
- [PAGE_NAME](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/BRANCH_NAME/)

Permissions guide

---

source/functions.txt
source/sync/error-handling/errors.txt

- https://jira.mongodb.org/browse/DOCSP-19232
- [Sync Errors](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-19232/sync/error-handling/errors/)

(DOCSP-19232): Separate handle sync errors and client log level

---

source/index.txt
source/release-notes.txt
source/release-notes/backend.txt
source/release-notes/changelogs/backend/changelog-backend-2021.rst
source/release-notes/changelogs/backend/changelog-backend-2022.rst
source/release-notes/dotnet.txt
source/release-notes/java.txt
source/release-notes/javascript.txt
source/release-notes/studio.txt
source/release-notes/swift.txt

- https://jira.mongodb.org/browse/DOCSP-22680
- [Release Notes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-22680/release-notes/backend)

(DOCSP-22680): Release notes 5/19 + porting release notes to app-services

---

source/manage-apps.txt
source/manage-apps/configure.txt
source/manage-apps/create.txt
source/manage-apps/delete.txt
source/manage-apps/deploy/automated.txt
source/manage-apps/deploy/manual.txt
source/sync.txt
source/sync/configure-realm-sync.txt
source/sync/configure-your-data-model.txt
source/sync/data-access-patterns.txt
source/sync/error-handling.txt
source/sync/learn.txt
source/triggers.txt

- https://jira.mongodb.org/browse/DOCSP-22787
- [Manage & Deploy Realm Apps](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-22787/manage-apps/)
- [Create Realm Apps](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-22787/manage-apps/create/)
- [Configure Realm Apps](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-22787/manage-apps/configure/)
- [Automate Realm App Deployment](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-22787/manage-apps/deploy/automated/)
- [Deploy Realm Apps Manually](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-22787/manage-apps/deploy/manual/)
- [Delete Realm …

(DOCSP-22787): Add bulleted indexes to container pages

---

source/openapi-admin-v3.yaml

- (DOCSP-16298): Admin API GraphQL Endpoints
- [Admin API > GraphQL API](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/graphql-admin/admin/api/v3/#tag/graphql)

(DOCSP-16298): Admin API GraphQL Endpoints

---

source/openapi-admin-v3.yaml

- (DOCS-15347): [Admin API] Configure resume token use with disable_token
- [Admin API > Resume a Suspended Trigger](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/disable_token/admin/api/v3/#operation/adminDeleteTrigger)

(DOCS-15347): [Admin API] Configure resume token use with disable_token

---

source/index.txt

- [App Services Landing Page](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/fix-landing-page-urls/)

Change landing page URLs to point to Realm instead of app-services

---

source/index.txt

- [App Services Landing Page](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/more-landing-page-url-updates/)

More tweaks to the landing page URLs

---

config/redirects

Fix redirects file prefix/base

---

source/openapi-admin-v3.yaml

- (DOCSP-22889): [Admin API] Rules for Data Source
- [Admin API > Rules](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-api-rules/admin/api/v3/#tag/rules)

(DOCSP-22889): [Admin API] Rules for Data Source

---

source/functions.txt

- [Functions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/functions-tweak/functions/)

Add a basic function example early on the page

---

source/sync/data-access-patterns/flexible-sync.txt

- https://jira.mongodb.org/browse/DOCSP-22492
N/A

(DOCSP-22492): Add Asymmetric Sync Ref

---

source/sync/data-access-patterns/sync-mode.txt

- https://jira.mongodb.org/browse/DOCSP-NNNNN
- [PAGE_NAME](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/BRANCH_NAME/)

Add link destinations for flexible/pbs for linking from kotlin SDK

---

source/manage-apps/configure/config/http_endpoints.txt
source/openapi-admin-v3.yaml

- Adds endpoints to get/create/update Data API configs + list all possible versions
- (DOCSP-21991): [Admin API] Get Data API Versions
- (DOCSP-22295): [Admin API] Get Data API Config
- (DOCSP-22309): [Admin API] Create Data API Config
- (DOCSP-22425): [Admin API] Update Data API Config
- [Admin API > Data API](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/data-api/admin/api/v3/#tag/data-api)

[Admin API] Data API Config

---

source/sync/data-access-patterns/flexible-sync-permissions-guide.txt

These apps will not be available in release.
Revert this change when ready to add.

Hide flex sync permissions template apps info - temporary

---

source/release-notes/changelogs/backend/changelog-backend-2022.rst

- https://jira.mongodb.org/browse/DOCSP-22987
- [Release Notes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-22987/release-notes/backend/)

(DOCSP-22987): Release notes, MongoDB World 2022

---

source/mongodb/crud-and-aggregation-apis.txt

- https://jira.mongodb.org/browse/DOCSP-23151
- [CRUD & Aggregation APIs/Database Command Availability](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-23151/mongodb/crud-and-aggregation-apis/#database-command-availability)

(DOCSP-23151): Add note about allowDiskUse support when running as system user

---

source/functions/mongodb/api/parameter-query.rst

- https://jira.mongodb.org/browse/DOCSP-23154
- [MongoDB API Reference](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-23154/functions/mongodb/api/#parameters-2)

(DOCSP-23154): Clarify that you can use evaluation, geospatial and bitwise in system functions

---

source/sync/data-access-patterns/flexible-sync.txt

- slack report
- [Flexible Sync - Data Access Patterns](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/link-to-enable-flex-sync/sync/data-access-patterns/flexible-sync/#enable-sync) (check out the "see also" link)

Link to Flexible Sync enable guide section instead of overall guide page

---

source/sync/data-access-patterns/flexible-sync.txt

- Dachary suggestion
- [Flexible Sync](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/kotlin-sdk-flexible-sync-link/sync/data-access-patterns/flexible-sync/#create-queries-in-your-client-application)

Kotlin SDK tab, flexible sync

---

source/sync/local-to-sync.txt

- https://jira.mongodb.org/browse/DOCSP-21972
- [Convert Local Realm to Synced Realm](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-21972/sync/local-to-sync/)

(DOCSP-21972): Convert Local to Synced Realm, Flexible Sync Edition

---

source/data-api/generated-endpoints.txt

_See also: Atlas Data API - https://github.com/10gen/cloud-docs/pull/3418_
- (DOCSP-23250): Data API Versions
- [Data API Endpoints](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/data-api/data-api/generated-endpoints/)

(DOCSP-23250): Data API Versions

---

source/users/delete-or-revoke.txt

NOTE: this is a small companion change to the work in the docs-realm repo (see https://github.com/mongodb/docs-realm/pull/1984)
NOTE 2: the link is currently not working; investigating why. 
https://jira.mongodb.org/browse/DOCSP-20094
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/delete_user/users/delete-or-revoke/#delete-a-user-in-the-sdk

add reference to new c# SDK docs

---

source/sync.txt
source/sync/event-library.txt

FWIW, the autobuilder check is failing on this PR because the linked Swift PR in the docs-realm repo (https://github.com/mongodb/docs-realm/pull/1917) hasn't been merged yet.
Before merging:
- https://jira.mongodb.org/browse/DOCSP-22203
- [Event Library](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-22203/sync/event-library/)

(DOCSP-22203): Create Event Library page

---

source/triggers/authentication-triggers.txt

Worked on an edit to the Authentication Triggers page in order to improve readability.
- https://jira.mongodb.org/browse/DOCSP-22280
- [Authentication Triggers](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-22280/triggers/authentication-triggers/)

(DOCSP-22280): Edited Authentication Triggers Page for Readability

---

source/release-notes/changelogs/backend/changelog-backend-2022.rst

- https://jira.mongodb.org/browse/DOCSP-23433
- [Release Notes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-23433/release-notes/backend/)

(DOCSP-23433): Release notes, 06/29/2022

---

source/includes/steps-configure-flexible-sync-api.yaml
source/includes/steps-configure-flexible-sync-cli.yaml
source/includes/steps-configure-flexible-sync-ui.yaml
source/sync/data-access-patterns/flexible-sync-permissions-guide.txt
source/sync/data-access-patterns/permissions.txt
source/sync/data-access-patterns/sync-mode.txt

- https://jira.mongodb.org/browse/DOCSP-23413
- https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/field-level-perms/sync/data-access-patterns/permissions/#flexible-sync-session-roles-and-rules

(DOCSP-23413): Field-level Permissions

---

source/openapi-admin-v3.yaml

- (DOCSP-23441): [Admin API] Default Rules
- [Admin API > Rules](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-default_rule/admin/api/v3/#operation/adminGetDefaultRule)

(DOCSP-23441): [Admin API] Default Rules

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-23432

(DOCSP-23432): Add docs release notes for w/e July 1, 2022

---

source/openapi-admin-v3.yaml

- (DOCSP-23554): [Admin API] Sample & Validate Documents
- [Admin API > Schemas > Sample & Validate Documents](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-validate_documents/admin/api/v3/#operation/adminValidateDocuments)

(DOCSP-23554): [Admin API] Sample & Validate Documents

---

source/data-api/custom-endpoints.txt

- (DOCSP-23297): Clarify custom endpoint route
- [Data API > Custom Endpoints](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/data-api-route/data-api/custom-endpoints/#endpoint-route)

(DOCSP-23297): Clarify custom endpoint route

---

source/data-api/custom-endpoints.txt
source/data-api/generated-endpoints.txt
source/includes/steps-create-a-service-webhook-cli.yaml
source/includes/steps-create-a-service-webhook-ui.yaml
source/includes/steps-define-a-function-realm-ui.yaml

- (DOCSP-23639): runAsSystemUser -> runAsSystem
- [Staged](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/script-runAsSystem/)

(DOCSP-23639): runAsSystemUser -> runAsSystem

---

source/sync/data-access-patterns/sync-mode.txt

- https://jira.mongodb.org/browse/DOCSP-23665
- [Data Access Patterns/Choose a Sync Mode](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-23665/sync/data-access-patterns/sync-mode/#partition-based-sync)

(DOCSP-23665): Remove mention of Flex Sync in Preview

---

source/authentication/email-password.txt

Updated Email/Password Authentication Page for readability. DRAFT.
- https://jira.mongodb.org/browse/DOCSP-22274
- [Email/Password Authentication](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-22274/authentication/email-password/)

(DOCSP-22274): Email/Password Readability Update

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-23626

(DOCSP-23626): Add docs release notes for w/e July 8, 2022

---

source/release-notes/changelogs/backend/changelog-backend-2022.rst
source/sync/data-access-patterns/flexible-sync-permissions-guide.txt

- Completes the MongoDB Realm rename
- [Flexible Sync Permissions Guide > Administrator Privileges](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/mongodb-realm/sync/data-access-patterns/flexible-sync-permissions-guide/#admin-privileges)
- [Release Notes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/mongodb-realm/release-notes/backend/#backend_20220325)

MongoDB Realm -> Atlas App Services

---

source/sync/data-model/sync-schema-overview.txt

- (DOCSP-23660): Define JSON Schema title in sync docs
- [Sync Schema Overview](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/schema-title/sync/data-model/sync-schema-overview/)

(DOCSP-23660): Define JSON Schema title in sync docs

---

source/migrate.txt

- fixing error in autobuilder
- [migrate](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/fix-migration-errors/migrate/)

Fix broken migration link to deleted iOS migration guide

---

source/index.txt
source/sync/data-access-patterns/flexible-sync-permissions-guide.txt
source/template-apps.txt

https://jira.mongodb.org/browse/DOCSP-23436
- https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/action_button/
- https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/action_button/template-apps/
- https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/action_button/sync/data-access-patterns/flexible-sync-permissions-guide/

Action button

---

source/reference/issues-and-workarounds.txt
source/triggers/database-triggers.txt

- https://jira.mongodb.org/browse/DOCS-15459
- [Known Issues and Workarounds](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-15459/reference/issues-and-workarounds/#known-issues—workarounds) (and minor changes to linked section, which already mentions "resume a suspended trigger" example and explains the reason for the error)

(DOCS-15459): Change Stream History Lost Trigger Errors

---

source/data-api.txt
source/reference/service-limitations.txt

- https://jira.mongodb.org/browse/DOCSP-23553
- [Service Limitations](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-23553/reference/service-limitations/)
- Will also update the Data API (Atlas) and Data API (App Services) documentation with a note linking to this section once this verbiage/linking is approved.

(DOCSP-23553): Apps do not support Private Link

---

source/functions.txt
source/users/delete-or-revoke.txt

- https://jira.mongodb.org/browse/DOCSP-23753
- [Delete App Services User](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-23753/users/delete-or-revoke/)

(DOCSP-23753): Add missing SDK APIs & custom func to delete users

---

source/data-api.txt
source/functions.txt
source/graphql.txt
source/index.txt
source/triggers/overview.txt

Updated App Services page titles to align with the new names. also adjusted the IA to shift the main 'Atlas' services up. documentation on the supporting services below. 
- n/a
- [App Services Docs](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/service_title_rename/)

Update section names & order for brand refresh

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-23720

(DOCSP-23720): Add docs release notes for w/e July 15, 2022

---

source/functions.txt

Update socket limit with net module

---

source/functions/mongodb/read.txt

- (DOCS-15497): Use ISODate format in Atlas Functions
- [Functions > Read](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/fn-date/functions/mongodb/read/)

(DOCS-15497): Use ISODate format in Atlas Functions

---

source/template-apps.txt

add two refs to the template app page to help me with [DOCSP-22738](https://jira.mongodb.org/browse/DOCSP-22738) via intersphinx. the rest of the changes for this ticket will be in the docs-realm repo.
n/a
n/a

Add create & explore template app refs

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-23843
- https://jira.mongodb.org/browse/DOCSP-23960

(DOCSP-23960): Add docs release notes for w/e July 22 and July 29

---

source/functions/mongodb/write.txt

- https://jira.mongodb.org/browse/DOCSP-24304
- [Write Data in MongoDB Atlas - Functions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-24304/functions/mongodb/write/#update): Update the field name in the Note callout to have two underscores

(DOCSP-24304): Add missing underscore to field name

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-24141

(DOCSP-24141): Add docs release notes for w/e August 5

---

source/openapi-admin-v3.yaml

- (DOCSP-23313): [Admin API] List supported app provider regions
- [GET /provider_regions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-provider_regions/admin/api/v3/#operation/adminListAppRegions)

(DOCSP-23313): [Admin API] List supported app provider regions

---

source/manage-apps/secure.txt

- https://jira.mongodb.org/browse/DOCSP-24603
- [Secure -> Firewall Configuration](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-24603/manage-apps/secure/#device-sync): Move the note about Device Sync into a new "Device Sync subsection", add the DNS Filtering info to that section

(DOCSP-24603): Add DNS filtering info for App Services Firewall Configuration

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-24524

(DOCSP-24524): Add docs release notes for w/e August 19

---

config/fixProductNamingConfig.json

```
find source -iname '*.txt' ! -path "source/sdk/java/api/*" | xargs node ~/projects/docdoctor fixProductNaming --snootyTomlPath ./snooty.toml --fixProductNamingJsonPath ./config/fixProductNamingConfig.json
```

Add fixProductNamingConfig for use with docdoctor

---

source/manage-apps/deploy/deployment-models-and-regions.txt

https://mongodb.slack.com/archives/CLY6HQWUE/p1661543367806659

Quickfix: Add GCP regions

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-24755

(DOCSP-24755): Add docs release notes for w/e August 26

---

source/openapi-admin-v3.yaml

- https://jira.mongodb.org/browse/DOCSP-24854
- [Admin API](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-24854/admin/api/v3/#operation/adminGetService): Retrieve a Service

(DOCSP-24854): Update success message for getting a service

---

source/sync/data-access-patterns/permissions.txt
source/sync/data-access-patterns/sync-mode.txt
source/sync/error-handling/errors.txt

- https://jira.mongodb.org/browse/DOCSP-23950
- https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/compensating-writes/sync/error-handling/errors/#flexible-sync-errors

(DOCSP-23950): Document compensating writes

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-24899

(DOCSP-24899): Add early docs release notes for w/e September 1

---

source/triggers/database-triggers.txt
source/triggers/overview.txt

... rather than inside the DB
- https://jira.mongodb.org/browse/DOCSP-24675
- 

(DOCSP-24675): Clarify that Atlas Triggers run on a serverless compute layer

---

source/data-api/generated-endpoints.txt
source/introduction.txt
source/openapi-admin-v3.yaml
source/services/github.txt
source/tutorial/jwt.txt
source/tutorials.txt

https://jira.mongodb.org/browse/DOCSP-25097
https://docs.google.com/spreadsheets/d/17XixUf9CuFsR4F8Gl44WD9cerbiq0zienOLC0RkXBUY/edit#gid=1479788457
- [Text changes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/link_fix/introduction/)
- [JWT Prereq changes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/link_fix/tutorial/jwt/)
- [Check various links](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/link_fix/admin/api/v3/#operation/adminGetDataApiConfig)

Link fixes and update tutorial text.

---

source/functions/mongodb/api.txt
source/includes/note-method-system-function-only.rst
source/release-notes/changelogs/backend/changelog-backend-2022.rst

- (DOCSP-24908) [BAAS] mdb.admin() & admin.getDBNames()
- [Functions > Query MongoDB Atlas > MongoDB API Reference](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/dbcommands/functions/mongodb/api/)

(DOCSP-24907) [BAAS] database.getCollectionNames()

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-24997

(DOCSP-24997): Add docs release notes for w/e September 9

---

source/release-notes/changelogs/backend/changelog-backend-2022.rst

add GCP regions to release notes
- https://jira.mongodb.org/browse/DOCSP-DOCSP-25013
- [App Services Release Notes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-25013/release-notes/backend/)

(DOCSP-25013): 2022-09-09 release notes

---

source/openapi-admin-v3.yaml

- (DOCSP-24918) [Admin API] Add service config definitions
- [Admin API > Data Sources & Services](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-api-services/admin/api/v3/#tag/services)

(DOCSP-24918) [Admin API] Add service config definitions

---

source/data-api/examples.txt

SEE ALSO: https://github.com/10gen/cloud-docs/pull/3661
- (DOCSP-24674) [Data API] Examples of custom rules
- [Data API Examples > Data Access Permissions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/data-api-rules/data-api/examples/#query-examples)

(DOCSP-24674) [Data API] Examples of custom rules

---

source/release-notes/changelogs/backend/changelog-backend-2022.rst

- Fixes inaccurate release note & removes build error
- [Changelog](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/fix-changelog/release-notes/backend/)

fix changelog

---

source/openapi-admin-v3.yaml

- (DOCSP-25373) [Admin API] Null Type Schema Validation
- [Admin API > Get/Set Null Type Schema Validation Setting](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-api-null-validation/https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#operation/adminGetNullTypeSchemaValidationSetting)

(DOCSP-25373) [Admin API] Null Type Schema Validation

---

source/openapi-admin-v3.yaml

- (DOCSP-25355) [Admin API] Full trigger definitions
- [Admin API > Triggers](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-api-triggers/admin/api/v3/#tag/triggers)

(DOCSP-25355) [Admin API] Full trigger definitions

---

source/services/replace-with-npm-modules.txt

- (DOCSP-25419) Fix AWS SDK example
- [Replace Services with npm Modules](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/fix-aws-example/services/replace-with-npm-modules/)

(DOCSP-25419) Fix AWS SDK example

---

source/cli/realm-cli-apps-create.txt
source/functions/context.txt
source/includes/appschema-mongodb.rst
source/includes/data-source-configuration.rst
source/manage-apps/configure/config/data_sources.txt
source/openapi-admin-v3.yaml

- (DOCSP-24445) [BAAS] Update App Services for Data Lake Name Change
- [Staged](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/datalake/)

(DOCSP-24445) [BAAS] Update App Services for Data Lake Name Change

---

source/functions/mongodb/aggregate.txt

- (DOCSP-24693) Atlas Search aggregation example
- [Functions > MongoDB > Aggregate](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/search-example/functions/mongodb/aggregate/#find-data-with-atlas-search)

(DOCSP-24693) Atlas Search aggregation example

---

source/triggers/database-triggers.txt

See also https://github.com/10gen/cloud-docs/pull/3713
- (DOCSP-25433) Remove 3.6 note & tweak db triggers
- [Database Triggers](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/triggers/triggers/database-triggers/)

(DOCSP-25433) Remove 3.6 note & tweak db triggers

---

source/sync/learn/protocol.txt

typo fix
- https://jira.mongodb.org/browse/DOCS-15640
- [Sync Protocol](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCS-15640/sync/learn/protocol)

(DOCS-15640): typo fix

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-25346

(DOCSP-25346): Add docs release notes for w/e September 23

---

source/openapi-admin-v3.yaml

- (DOCSP-25463) [Admin API] App CRUD & Deployment
- [Admin API > Applications](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-api-apps/admin/api/v3/#tag/apps)

(DOCSP-25463) [Admin API] App CRUD & Deployment

---

source/includes/valid-deployment-regions.rst
source/manage-apps/configure/config/app.txt
source/manage-apps/create/create-with-cli.txt
source/manage-apps/deploy/deployment-models-and-regions.txt

- Update **Cloud Deployment Regions** to be a comprehensive reference table
- Update descriptions of global/local apps
- Remove included list of deployment regions - rely on linking to the table instead.
- (DOCSP-25492) Update Cloud Deployment Regions
- [Deployment Models & Regions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/deployment-regions/manage-apps/deploy/deployment-models-and-regions)
- [Config Files > App](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/deployment-regions/manage-apps/configure/config/app/#configuration)

(DOCSP-25492) Update Cloud Deployment Regions

---

source/openapi-admin-v3.yaml

- (DOCSP-25747) [Admin API] Get & Redeploy a Deployment
- [Admin API > Deployment](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-redeploy/admin/api/v3/#tag/deploy)

(DOCSP-25747) [Admin API] Get & Redeploy a Deployment

---

source/sync/learn/overview.txt

- https://jira.mongodb.org/browse/DOCSP-25740
- 

(DOCSP-25740): Link to Realm SDKs page from Device Sync intro

---

source/manage-apps/deploy/deployment-models-and-regions.txt
source/openapi-admin-v3.yaml

- (DOCSP-25806) Remove Ohio and Sao Paolo from local regions
- [Deployment Models & Regions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/regions/manage-apps/deploy/deployment-models-and-regions/)
- [Admin API](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/regions/admin/api/v3/#operation/adminCreateApplication)

(DOCSP-25806) Remove Ohio and Sao Paulo from local regions

---

source/functions/mongodb/aggregate.txt
source/includes/note-atlas-search-search_meta.rst
source/mongodb/crud-and-aggregation-apis.txt

- (DOCSP-25749) $$SEARCH_META aggregation variable limitation
- [Find Data with Atlas Search](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/search-meta/functions/mongodb/aggregate/#find-data-with-atlas-search)
- [Aggregation Pipeline Stage Availability](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/search-meta/mongodb/crud-and-aggregation-apis/#aggregation-pipeline-stage-availability)

(DOCSP-25749) $$SEARCH_META aggregation variable limitation

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-25768

(DOCSP-25768): Add docs release notes for w/e October 14

---

source/includes/trigger-auto-resume.rst
source/manage-apps/configure/config/triggers.txt
source/openapi-admin-v3.yaml
source/triggers/database-triggers.txt

Documentation for auto-resume Database Triggers configuration. 
- https://jira.mongodb.org/browse/DOCSP-25443
- [Database Triggers](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-25443/triggers/database-triggers#)
- [Trigger configuration reference](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-25443/manage-apps/configure/config/triggers/#database-triggers)
- [API reference (Database Trigger object schema)](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-25443/admin/api/v3/#operation/adminCreateTrigger)

(DOCSP-25443): Auto-resume Database Triggers config

---

source/functions/context.txt

- Adds `context.app` to Function Context
- Do not merge until https://jira.mongodb.org/browse/BAAS-17460 is live
- (DOCSP-25159) [BAAS] Access App metadata with function context
- [Functions > Context](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/context-app/functions/context/#std-label-context-app)

(DOCSP-25159) [BAAS] Access App metadata with function context

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-25913

(DOCSP-25913): Add docs release notes for w/e October 21

---

source/includes/note-third-party-services-deprecation.rst

- https://jira.mongodb.org/browse/DOCSP-24888
- [Third-Party Services [Deprecated]](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-24888-BAAS-Service-Deprecation/reference/services/)

(DOCSP-24888): Changed Date to reflect updated deprecation date in European format

---

source/examples/generated/flutter/tutorial/item_viewmodel.snippet.item-viewmodel.dart.modified.rst
source/tutorial/flutter.txt

- small clarifications to the flutter tutorial based on feedback from Google Dev Advocate
- https://jira.mongodb.org/browse/DOCSP-26198
- [Flutter tutorial](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26198/tutorial/flutter)

Flutter tutorial clarification 

---

source/sync.txt

- Workshopping with Angela
- Re-work intro clincher
- Change feature card order
- Change "conflict resolution" card to be about general robustness/security/permissions
- Move security features to bottom of page
- N/A
- https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/sync-landing-2/sync/

Update sync landing page

---

docs-release-notes.md
source/sync.txt

Note for reviewer: In preparing release notes, I realized we missed adding a new section to the Sync ToC, so I snuck that in here.
- https://jira.mongodb.org/browse/DOCSP-26072

(DOCSP-26072): Add docs release notes for w/e October 28

---

source/openapi-admin-v3.yaml

- Adds new endpoint
- https://jira.mongodb.org/browse/DOCSP-25113
- https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/metrics-api/admin/api/v3/#tag/metrics

(DOCSP-25113): Document Metrics endpoint

---

source/tutorial/backend.txt

This PR is a medium-sized update to the GitHub Issue Tracker tutorial. The updates include changes based on reader feedback, the style guide, UI shifts, and workflow improvements.
The reader feedback in [DOCSP-25715](https://jira.mongodb.org/browse/DOCSP-25715) identified 3 issues. The first 2 are fixed the same way: changing the endpoint function's authentication settings to **System**. The 3rd is most likely because the pasted value didn't have surrounding quotation marks (it must be valid JSON). Making these things clearer is the bulk of this PR.
Perhaps the largest change is that I added a new function detailing how to [update a function's authentication settings](https://github.com/mongodb/docs-app-services/pull/205/files#diff-4e51bd7969481a560787c1d17618df0ed338c58928bb09c1cea0ae9407 …

(DOCSP-25715) GitHub Issue Tracker refresh

---

source/reference/template-apps.txt

- https://jira.mongodb.org/browse/DOCSP-24326
- [Template Apps](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-24326-update-template-app-descriptions/reference/template-apps/#template-apps-available) table descriptions

(DOCSP-24326): Updating template app descriptions

---

source/includes/triggers-examples-github.rst
source/triggers.txt

fix link to triggers example repo

fix trigger example repo link

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-26222

(DOCSP-26222): Add docs release notes for w/e November 4

---

source/data-api/generated-endpoints.txt
source/manage-apps/deploy/deployment-models-and-regions.txt

See also https://github.com/10gen/cloud-docs/pull/3873
- (DOCSP-26235) Clarify cloud, region, and region_id
- [Cloud Deployment Regions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/deployment-regions/manage-apps/deploy/deployment-models-and-regions/#cloud-deployment-regions)
- [Data API Base URL](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/deployment-regions/data-api/generated-endpoints/#base-url)

(DOCSP-26235) Clarify cloud, region, and region_id

---

source/triggers/disable.txt

https://jira.mongodb.org/browse/DOCSP-25435
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-25435/triggers/disable/#restoring-from-a-snapshot

Docsp-25435: Triggers during restore

---

source/openapi-admin-v3.yaml

- (DOCSP-26239) [Admin API] Data API Validation Method
- (DOCSP-26209) [Admin API] Data API function_name -> function_id
- [Admin API](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/name2id/admin/api/v3/#tag/data-api)

[Admin API] Data API Endpoint Bugs

---

source/manage-apps/configure/config/sync.txt

https://jira.mongodb.org/browse/DOCSP-24305 
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-24305/manage-apps/configure/config/sync/

change wording about read-when-write

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-26354

(DOCSP-26354): Add docs release notes for w/e November 11

---

source/hosting/file-metadata-attributes.txt

- (DOCSP-4180) Hosted file metadata: Website-Redirect-Location
- [Hosting > File Metadata Attributes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/hosting-metadata/hosting/file-metadata-attributes/#website-redirect-location)

(DOCSP-4180) Hosted file metadata: Website-Redirect-Location

---

source/openapi-admin-v3.yaml

- (DOCSP-26280) [Admin API] Deployment Config
- [Admin API > Deployment](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-deployment/admin/api/v3/#tag/deploy/operation/adminGetDeploymentConfig)

(DOCSP-26280) [Admin API] Deployment Config

---

source/openapi-admin-v3.yaml

- (DOCSP-25909) [Admin API] Get all apps accepts multiple product types
- [Admin API > Apps](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-product-types/admin/api/v3/#tag/apps/operation/adminListApplications)

(DOCSP-25909) [Admin API] Get all apps accepts multiple product types

---

source/openapi-admin-v3.yaml

- The primary workflow for this ticket is covered by the monitoring/alerts project, but adding these endpoints for completeness
- (DOCSP-15200) Realm Sync Monitoring Endpoints
- [OpenAPI > Event Processors](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/sync-monitoring-endpoints/admin/api/v3/#tag/event-subscriptions)

(DOCSP-15200) Realm Sync Monitoring Endpoints

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-26511

(DOCSP-26511): Add docs release notes for w/e November 18

---

source/openapi-admin-v3.yaml

- (DOCSP-26408) [Admin API] List pending user registrations
- [Admin API > List pending users](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-pending-users/admin/api/v3/#tag/users/operation/adminListPendingUsers)

(DOCSP-26408) [Admin API] List pending user registrations

---

source/openapi-admin-v3.yaml

- (DOCSP-26523) [Admin API] Auth Providers
- [Admin API > Auth Providers](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-auth-providers/admin/api/v3/#tag/authproviders)

(DOCSP-26523) [Admin API] Auth Providers

---

config/redirects

- https://jira.mongodb.org/browse/DOCSP-NNNNN
- [PAGE_NAME](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/BRANCH_NAME/)

Add missing redirects

---

source/sync/get-started.txt

- Adds query/subscription info back that was eagerly deleted during refactor, but has value in cross-linking
- N/A
- https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/restore-query-subscription/sync/get-started/

Restore "Create Queries in Your Client Application" blurb

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-26634

(DOCSP-26634): Add docs release notes for w/e November 25

---

.github/pull_request_template.md

See https://github.com/mongodb/docs-realm/pull/2311

(DOCSP-19610): Add reminder checklist to PR template

---

source/openapi-admin-v3.yaml

- (DOCSP-26207) Construct an Endpoint/Data API Base URL
- [Admin API > Construct a Data API Base URL](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/construct-base-url/admin/api/v3/#tag/data-api/Construct-a-Data-API-Base-URL)
- [Admin API > Construct a Custom HTTPS Endpoint Base URL](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/construct-base-url/admin/api/v3/#tag/endpoints/Construct-a-Custom-HTTPS-Endpoint-Base-URL)

(DOCSP-26207) Construct an Endpoint/Data API Base URL

---

source/reference/service-limitations.txt
source/triggers/database-triggers.txt

- https://jira.mongodb.org/browse/DOCSP-26686
- https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/change-streams-limits/

(DOCSP-26686): Remove stream request limits

---

source/release-notes/backend.txt

Release notes for 30 Nov 2022
- https://jira.mongodb.org/browse/DOCSP-26743
- [Release notes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DCOSP-26743/release-notes/backend/)

(DOCSP-26743): Release notes for 30 Nov 2022

---

source/functions.txt

fix wrong link and text 
n/a
- [Functions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/func_fix_link/functions)

fix wrong link

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-26719

(DOCSP-26719): Add docs release notes for w/e December 2

---

source/sync/data-model/create-a-schema.txt
source/sync/data-model/data-model-map.txt

- https://jira.mongodb.org/browse/DOCSP-26876
- [Create a Schema # Open a Realm with the Realm Object Schema](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/quickfix-rn-rST/sync/data-model/create-a-schema/#open-a-realm-with-the-realm-object-schema)
- [Data Model Map # Property Types](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/quickfix-rn-rST/sync/data-model/data-model-map/#property-types)
- [N/A] Checked/updated Admin API
- [N/A] Checked/updated CLI reference

Quick fix React Native refactor links

---

source/sync/data-model/update-schema.txt

- https://jira.mongodb.org/browse/DOCSP-26838
- [Update Your Data Model](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26838/sync/data-model/update-schema/#how-to-change-a-property-name)

(DOCSP-26838): Add Swift SDK ref to property naming callout

---

source/cli.txt
source/includes/event-processor-example.rst
source/openapi-admin-v3.yaml
source/triggers/aws-eventbridge.txt

- https://jira.mongodb.org/browse/DOCSP-26868
- [AWS EventBridge Triggers](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26868/triggers/aws-eventbridge/)
- [App Services Admin API ](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26868/admin/api/v3/#tag/triggers/operation/adminCreateTrigger)
- [Realm CLI](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26868/cli/) - small typo fix
- [N/A] Create Jira ticket for corresponding docs-realm update(s), if any

(DOCSP-26868): Add "Enable Extended JSON" configuration option

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-27024

(DOCSP-27024): Add docs release notes for w/e December 16

---

source/sync/get-started.txt

- https://jira.mongodb.org/browse/DOCSP-26867
- [Device Sync/Get Started](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26867/sync/get-started/#choose-an-sdk)

(DOCSP-26867): Add link to C++ SDK docs, alphabetize list of SDKs

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-27121
N/A
- [N/A] Create Jira ticket for corresponding docs-realm update(s), if any
- [N/A] Checked/updated Admin API
- [N/A] Checked/updated CLI reference

(DOCSP-27121): Release Notes for 12/23/2022 for App Services

---

source/openapi-admin-v3.yaml

- https://jira.mongodb.org/browse/DOCSP-26778
- [Admin API - adminGetMetrics](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/docsp-26778-metrics-query-params/admin/api/v3/#tag/metrics/operation/adminGetMetrics)

(DOCSP-26778): Adding examples for valid query params in adminGetMetrics endpoint

---

docs-release-notes.md

Docs release notes for December 30, 2022
- https://jira.mongodb.org/browse/DOCSP-27187

Add docs release notes for w/e December 30

---

source/sync/configure/pause-or-terminate-sync.txt

- https://jira.mongodb.org/browse/DOCSP-27213
- [Pause or Terminate Sync](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27213/sync/configure/pause-or-terminate-sync/#terminate-sync)

(DOCSP-27213): Update the list of things that require you to terminate sync

---

snooty.toml
source/authentication/custom-jwt.txt
source/includes/appschema-functions.rst
source/includes/appschema-services.rst
source/includes/user-object-fields.rst
source/index.txt
source/manage-apps/configure/config/functions.txt
source/manage-apps/configure/config/http_endpoints.txt
source/manage-apps/deploy.txt
source/mongodb/define-roles-and-permissions.txt
source/mongodb/wire-protocol.txt
source/reference/authenticate-http-client-requests.txt
source/rules.txt
source/rules/examples.txt
source/services/github.txt
source/services/http.txt
source/services/twilio.txt
source/triggers/authentication-triggers.txt
source/tutorial/backend.txt
source/users.txt

- https://jira.mongodb.org/browse/DOCSP-26927
- [Authenticate & Manage Users](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26927/users/)

(DOCSP-26927): IA Refresh '[Section] Authenticate & Manage Users'

---

source/functions/javascript-support.txt
source/services/aws.txt

- Apparently mangled by docdoctor
- https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/fix-monospace-titles/

Fix monospace in titles

---

source/sync/data-model/create-a-schema.txt

- https://jira.mongodb.org/browse/DOCSP-26976
- [Create a Data Model](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26976/sync/data-model/create-a-schema/#edit-your-realm-object-schema). Tab group at bottom of step 2 now includes C++.
- [ n/a ] Create Jira ticket for corresponding docs-realm update(s), if any
- [ n/a ] Checked/updated Admin API
- [ n/a ] Checked/updated CLI reference
<image src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/10b82089-c0b9-4982-822c-64d544e8e0c5/dci1kyk-d267f960-c75f-4469-9c08-36ad60ecaf89.jpg/v1/fill/w_1280,h_1285,q_75,strp/cuttlefish_wearing_a …

(DOCSP-26976): Add link to C++ SDK object model page

---

source/reference/service-limitations.txt

I addressed all of the concerns outlined in the Jira ticket except for the Rules section. As noted there, the Rules section will be updated by other existing work.
- https://jira.mongodb.org/browse/DOCSP-27195
- [Service Limitations](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27195/reference/service-limitations/#rules)
- [ n/a ] Create Jira ticket for corresponding docs-realm update(s), if any
- [ n/a ] Checked/updated Admin API
- [ n/a ] Checked/updated CLI reference
<image src="https://ih0.redbubble.net/image.82683872.7091/flat,1000x1000,075,f.jpg" width="350">

(DOCSP-27195): Correct information about some App Services limitations

---

source/tutorial/swiftui.txt

- https://jira.mongodb.org/browse/DOCSP-27230
- [SwiftUI iOS Tutorial](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27230/tutorial/swiftui/)

(DOCSP-27230): Update SwiftUI tutorial for v2 template app

---

source/hosting.txt
source/index.txt

- https://jira.mongodb.org/browse/DOCSP-26940
- [Host Files](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26940/hosting)

(DOCSP-26940): IA Refresh '[Section] Host Files'

---

config/redirects
source/authentication/api-key.txt
source/users.txt
source/users/manage.txt

- https://jira.mongodb.org/browse/DOCSP-26931
- [Manage User Accounts](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26931/users/manage)

(DOCSP-26931): IA Refresh '[Port] Manage User Accounts (/users/manage)'

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-27211

(DOCSP-27211): Add docs release notes for w/e January 6, 2023

---

source/reference/template-apps.txt

Note: We shouldn't merge this PR until the PR that updates the READMEs in the template apps repository gets merged (PR [#126](https://github.com/mongodb-university/realm-template-apps/pull/126))
- https://jira.mongodb.org/browse/DOCSP-27237
- [Template Apps](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27237/reference/template-apps/)

(DOCSP-27237): Template App page updates

---

source/includes/tutorial-request-for-feedback-note.rst
source/tutorial/kotlin.txt

- Update Kotlin tutorial with v2 app functionality (I used language from the [SwiftUI v2 template tutorial PR](https://github.com/mongodb/docs-app-services/pull/276/files#diff-d9f63f6fb3aa07493b5e55a88e6647bedfded0df4a8847c03e2b398518a82db6R35-R37) for consistency). 
- Update code samples and procedures as needed to work in Compose-based app ([gist](https://gist.github.com/cbullinger/dc848f898bf9e9720708cfe7e2c093d8) of affected code with tutorial steps implemented).
- https://jira.mongodb.org/browse/DOCSP-27234
- [Android With Kotlin Tutorial](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/docsp-27234-kotlin-v2-template/tutorial/kotlin/) …

(DOCSP-27234): Updating Kotlin tutorial for v2 Compose app

---

source/tutorial/swiftui.txt

- https://jira.mongodb.org/browse/DOCSP-27362
- [Device Sync Tutorial - SwiftUI](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27362/tutorial/swiftui/)

(DOCSP-27362): SwiftUI Tutorial: Minor improvements

---

source/manage-apps/configure/config/auth.txt
source/openapi-admin-v3.yaml
source/users/enable-custom-user-data.txt

- (DOCSP-26904) [BAAS] Configure user creation function (CLI/API)
- [Enable Custom User Data > User Creation Function](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/user-creation-fn/users/enable-custom-user-data/)
- [Config > Custom User Data](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/user-creation-fn/manage-apps/configure/config/auth/#custom-user-data)
- [Admin API > Custom User Data](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/user-creation-fn/admin/api/v3/#tag/custom-user-data)

(DOCSP-26904) [BAAS] Configure user creation function (CLI/API)

---

source/release-notes/backend.txt

Backend release notes for Jan 11, 2023
- https://jira.mongodb.org/browse/DOCSP-27337
- [Backend release notes ](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27337/release-notes/backend)

(DOCSP-27337): Backend release notes for Jan 11, 2023

---

source/includes/apple-account-deletion-requirements.rst
source/users/create.txt

- Add info about Authentication Providers and Identity (Create a new account, Link to an Existing Account)
- Port the existing Create an App page + add tabs for Admin API / CLI
https://www.mongodb.com/docs/atlas/app-services/users/create/
- https://jira.mongodb.org/browse/DOCSP-26928
- [Create an App User](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26928/users/create)

(DOCSP-26928): IA Refresh '[Port] Create an App User (/users/create)'

---

source/sync/go-to-production/compact-disk.txt

- https://jira.mongodb.org/browse/DOCSP-27204
- [Compact an Atlas Volume](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27204/sync/go-to-production/compact-disk/#steps-to-compact-and-reclaim-disk-space)

(DOCSP-27204) Remove erroneous info about rolling resync

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-27334

(DOCSP-27334): Add docs release notes for w/e January 13, 2023

---

config/redirects
snooty.toml
source/apps.txt
source/index.txt
source/security.txt

Port existing page to serve as a succinct overview of security + link out to deeper topics
- https://jira.mongodb.org/browse/DOCSP-26933
- [Secure Your App](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-26933/security)

(DOCSP-26933): IA refresh '[Section] Secure Your App (/security)'

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-27421

(DOCSP-27421): Add docs release notes for w/e January 20

---

source/apps.txt
source/apps/copy.txt
source/apps/create.txt
source/apps/export.txt
source/apps/update.txt
source/authentication/custom-jwt.txt
source/cli/realm-cli-reference-v1.txt
source/functions/test.txt
source/reference/config/template-expansions.txt
source/reference/find-your-project-or-app-id.txt
source/reference/partition-based-sync.txt
source/reference/template-apps.txt
source/sync/app-builder/local-to-sync.txt
source/sync/app-builder/stream-data-from-client-to-atlas.txt
source/sync/app-builder/sync-data-in-atlas-with-client.txt
source/sync/app-builder/sync-data-in-client-with-atlas.txt
source/sync/get-started.txt

- (DOCSP-27419) App Section Cleanup
- [Create an App](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/ia-apps-cleanup/apps/create/)

IA REFRESH - (DOCSP-27419) App Section Cleanup

---

source/tutorial/react-native.txt

Didn't create a Jira ticket for this small update. Because the user experience differs depending on how they get the client code, I changed how we talk about the path to the client code.
- [React Native Tutorial](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/react-native-tutorial-v2-updates/tutorial/react-native/)

(RN tutorial v2) Update path instructions

---

source/release-notes/backend.txt

> **Warning**
>
> Do not merge until after https://github.com/mongodb/docs-app-services/pull/216 is merged. 
Release notes for 25 January, 2023
- https://jira.mongodb.org/browse/DOCSP-27549
- [App Services Changelog](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27549/release-notes/backend/)

(DOCSP-27549): Release notes for 25 January, 2023

---

source/manage-apps/secure.txt

https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/rules-v2-secure/

Update 'secure' page

---

source/sync/configure/enable-sync.txt
source/sync/get-started.txt

https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/sync-get-started/

Update sync enable and get started pages

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-27548

(DOCSP-27548): Add docs release notes for w/e January 27

---

source/tutorial/kotlin.txt

- https://jira.mongodb.org/browse/DOCS-15835
- [Android With Kotlin Tutorial](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCS-15835/tutorial/kotlin/)

DOCS-15835 Clarity Improvements to Kotlin Tutorial

---

source/includes/tip-role-order-config-files.rst
source/manage-apps/configure/config/data_sources.txt
source/mongodb/tables/role-configuration.rst
source/rules/roles.txt
source/sync/configure/permissions.txt
source/sync/configure/sync-settings.txt

https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/sync-settings/rules/roles/

Update general roles page

---

source/security.txt
source/security/developer-access.txt

- (DOCSP-26937) [Port] Control Developer Access (/security/developer-access)
- [Secure Your App > Control Developer Access](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/ia-security/security/developer-access/)

(DOCSP-26937) [Port] Control Developer Access (/security/developer-access)

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-27652

(DOCSP-27652): Add docs release notes for w/e February 3

---

source/data-access.txt
source/mongodb.txt
source/mongodb/data-access.txt

Add page explaining MongoDB Data Access and how it relates to App Services / Realm SDKs.
- https://jira.mongodb.org/browse/DOCSP-27345
- [Query Atlas from Client Apps](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27345/mongodb/data-access)

(DOCSP-27345): MongoDB Data Access page

---

source/reference/service-limitations.txt

- https://jira.mongodb.org/browse/DOCSP-27743
- [Service Limitations](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27743/reference/service-limitations/#request-traffic)

DOCSP-27743 Increase app request limit to 10k

---

source/apps/change-deployment-models.txt
source/includes/prereqs/api-project-app-id.rst
source/includes/prereqs/atlas-account.rst
source/includes/prereqs/atlas-admin-api-key.rst
source/manage-apps/deploy.txt
source/openapi-admin-v3.yaml
source/reference/find-your-project-or-app-id.txt

- (DOCSP-26666) Changeable Deployment Models
- [Change Deployment Models](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/changeable-deployment-models/apps/change-deployment-models/)
- [Admin API > (GET|PUT) /groups/{groupId}/apps/{appId}/deployment_migration](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/changeable-deployment-models/admin/api/v3/#tag/deploy/operation/adminGetDeploymentMigration)
- included in this PR
- not supported via CLI at this time

(DOCSP-26666) Changeable Deployment Models

---

source/functions/context.txt
source/values-and-secrets.txt
source/values-and-secrets/access-a-value.txt

- (DOCSP-27880) Fix context.environment.values link
- [Values & Secrets](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/typo/values-and-secrets/)

(DOCSP-27880) Fix context.environment.values link

---

source/release-notes/backend.txt

8 Feb 23 release notes
- https://jira.mongodb.org/browse/DOCSP-27862
- [Changelog](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27862/)

(DOCSP-27862): 8 Feb 23 release notes

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-27840

(DOCSP-27840): Add docs release notes for w/e February 10

---

source/index.txt
source/mongodb.txt

- (DOCSP-26926) [Section] Connect to MongoDB Data Sources
- [Connect to MongoDB Data Sources](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/ia-mongodb/mongodb/)

(DOCSP-26926) [Section] Connect to MongoDB Data Sources

---

source/apps/metadata.txt

- (DOCSP-28012) Add CLI steps to Find Your App ID
- [Get App Metadata](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/ia-metadata/apps/metadata/)

(DOCSP-28012) Add CLI steps to Find Your App ID

---

snooty.toml
source/data-model.txt
source/index.txt
source/schemas.txt

- (DOCSP-26938) [Section] Define a Data Model
- [Define a Data Model](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/ia-data-model/data-model/)

(DOCSP-26938) [Section] Define a Data Model

---

source/apps/copy.txt
source/apps/create.txt
source/apps/metadata.txt
source/reference.txt

Just adding back some missing refs that are causing build errors in docs-realm, and removing a duplicate ToC entry for Template Apps
- N/A

Small fixes for IA updates

---

source/get-started.txt
source/includes/tutorial-learn-more-template-app.rst
source/reference/template-apps.txt
source/tutorial/dotnet.txt
source/tutorial/flutter.txt
source/tutorial/kotlin.txt
source/tutorial/react-native.txt
source/tutorial/swiftui.txt

- https://jira.mongodb.org/browse/DOCSP-28098
- [Get Started](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/docsp-28098-template-cta/get-started/) 
- Device Sync Tutorials for each SDK - updated "Start with the Template" section
- [Template Apps](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/docsp-28098-template-cta/reference/template-apps/)

(DOCSP-28098): Update Template App CTA wording

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-27990

(DOCSP-27990): Add docs release notes for w/e February 17

---

source/users/custom-metadata.txt

No Jira ticket - just fixing some build errors in docs-realm.
- [Define Custom User Metadata](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/missing-ref-target-fixes/users/custom-metadata/)

Fix missing ref target and conflated SDK links

---

source/release-notes/backend.txt

External Release Notes - Feb 23, 2023
- https://jira.mongodb.org/browse/DOCSP-28186
- [Release Notes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-28186/release-notes/backend)

(DOCSP-28186): External Release Notes - Feb 23, 2023

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-28162

(DOCSP-28162): Add docs release notes for w/e February 24

---

source/rules/sync-compatibility.txt

Per direct feedback from @jonatlee

Clarify not recommending manual migration

---

source/sync/data-model/update-schema.txt

- https://jira.mongodb.org/browse/DOCSP-27364
- [Sync/Update Your Data Model](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27364/sync/data-model/update-schema/)

(DOCSP-27364): Update details about which documents resync with additive changes

---

source/tutorial/dotnet.txt

https://jira.mongodb.org/browse/DOCSP-27595
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/docsp-27595/tutorial/dotnet/

update tempalte setup as per flutter tutorial

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-28277

(DOCSP-28277): Add docs release notes for w/e March 3

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-28408

(DOCSP-28408): Add docs release notes for w/e March 10

---

source/sync/go-to-production/optimize-sync-atlas-usage.txt

- https://jira.mongodb.org/browse/DOCS-15812
- [Optimize Sync Atlas Usage](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCS-15812/sync/go-to-production/optimize-sync-atlas-usage/)

DOCSP-15812 Clarity on Sync for  Optimizing Sync Utility Data

---

source/tutorial/flutter.txt

Flutter device sync tutorial fixes
- https://jira.mongodb.org/browse/DOCSP-27576
- [Flutter Device Sync tutorial](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27576/tutorial/flutter/)

(DOCSP-27576): Flutter Device Sync tutorial fixes

---

source/includes/define-custom-user-data.rst
source/users/custom-metadata.txt
source/users/sessions.txt

- (DOCSP-27081) [UI] Configure user session refresh token expiration
- [Manage User Sessions > Configure Refresh Token Expiration](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/refresh-ui/users/sessions/#std-label-refresh-token-expiration)

(DOCSP-27081) [UI] Configure user session refresh token expiration

---

source/includes/define-custom-user-data.rst
source/users/custom-metadata.txt
source/users/sessions.txt

Reverts mongodb/docs-app-services#394
I merged it too early - whoops!

Revert "(DOCSP-27081) [UI] Configure user session refresh token expiration"

---

source/release-notes/backend.txt

Release notes - 16 March 2023
- https://jira.mongodb.org/browse/DOCSP-28553
- [Backend Release Notes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-28553/release-notes/backend/)

(DOCSP-28553): Release notes - 16 March 2023

---

source/reference/partition-based-sync.txt

- https://jira.mongodb.org/browse/DOCS-15891
- [Partition Based Sync](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-15891/reference/partition-based-sync/#partition)

DOCS-15891 Unnecessary link on PBS page

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-28549

(DOCSP-28549): Add docs release notes for w/e March 17

---

source/openapi-admin-v3.yaml

- (DOCSP-27239) [Admin API] App Logs
- [Admin API > Get Logs](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-logs/admin/api/v3/#operation/adminGetLogs)

(DOCSP-27239) [Admin API] App Logs

---

source/release-notes/backend.txt

Release notes 29 March, 2023
- https://jira.mongodb.org/browse/DOCSP-28850
- [Release notes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-28850/release-notes/backend/)

(DOCSP-28850): Release notes 29 March, 2023

---

source/includes/important-stop-tiered-sync-server.rst
source/sync/app-builder/tiered-device-sync/index.txt

- https://jira.mongodb.org/browse/DOCSP-28829
- [Tiered Device Sync Guide](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-28829/sync/app-builder/tiered-device-sync/index/)

(DOCSP-28829): Revise Tiered Sync Guide for private pre-alpha context

---

source/sync/data-model/update-schema.txt

- https://jira.mongodb.org/browse/DOCSP-28936
- [Update Your Data Model](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-28936/sync/data-model/update-schema/)

(DOCSP-28936): Remove erroneous schema migration info from page

---

source/openapi-admin-v3.yaml

This should have been in https://github.com/mongodb/docs-app-services/pull/404 but was not included

function name begone!

---

source/authentication/email-password.txt

- https://jira.mongodb.org/browse/DOCSP-27793
- [Email/Password Authentication](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-27793/authentication/email-password/#run-a-password-reset-function)

DOCSP-27793 Update copy for additional default reset password parameter

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-28827

(DOCSP-28827): Add docs release notes for w/e March 31

---

.github/workflows/test-data-api.yml
examples/data-api/README.md
examples/data-api/bluehawk.sh
examples/data-api/check.sh
examples/data-api/generated-endpoints.sh
source/data-api.txt
source/data-api/generated-endpoints.txt
source/data-api/snippets/generated-endpoints.snippet.aggregate.sh
source/data-api/snippets/generated-endpoints.snippet.deleteMany.sh
source/data-api/snippets/generated-endpoints.snippet.deleteOne.sh
source/data-api/snippets/generated-endpoints.snippet.find.sh
source/data-api/snippets/generated-endpoints.snippet.findOne.sh
source/data-api/snippets/generated-endpoints.snippet.hello-world.sh
source/data-api/snippets/generated-endpoints.snippet.insertMany.sh
source/data-api/snippets/generated-endpoints.snippet.insertOne.sh
source/data-api/snippets/generated-endpoints.snippet.replaceOne.sh
source/data-api/snippets/generated-endpoints.snippet.updateMany.sh
source/data-api/snippets/generated-endpoints.snippet.updateOne.sh

- Adds unit tested examples for (some) Data API examples based on the [shunit2](https://github.com/kward/shunit2) testing framework
- Adds a GitHub Action to automatically run the tests and `bluehawk check`.
- (DOCSP-27603) [Spike] A test framework for cURL requests
- [Data API](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/data-api-bluehawk/data-api/)

(DOCSP-27603) [Spike] A test framework for cURL requests

---

source/users/custom-metadata.txt

Add link to new Custom User Data - Kotlin SDK page added in https://github.com/mongodb/docs-realm/pull/2695
- https://jira.mongodb.org/browse/DOCSP-28852
- [Define Custom User Metadata](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/docsp-28852-kotlin-user-custom-data/users/custom-metadata/#access-custom-user-data-from-a-client-application)

(DOCSP-28852): Add Kotlin Custom User Data link

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-28947

(DOCSP-28947) Add docs release notes for w/e April 07

---

source/rules/sync-compatibility.txt

- https://jira.mongodb.org/browse/DOCSP-29047
- [Device-Sync Compatible Permissions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-29047/rules/sync-compatibility/)

(DOCSP-29047): Fix a list formatting issue

---

source/sync/configure/pause-or-terminate-sync.txt

- (DOCSP-29068) Finalize drafts before terminating sync
- [Terminate Sync](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/term/sync/configure/pause-or-terminate-sync/)

(DOCSP-29068) Finalize drafts before terminating sync

---

redocly.yaml
source/openapi-admin-v3.yaml

- (DOCSP-29274) [Admin API] Private Endpoints
- [Admin API > Security > VPC Private Endpoints](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/privatelink/admin/api/v3/#tag/security)

(DOCSP-29274) [Admin API] Private Endpoints

---

source/triggers/database-triggers.txt

- https://jira.mongodb.org/browse/DOCSP-28809
- https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/match-fixes/

(DOCSP-28809): Match recommendations & testing

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-29273

(DOCSP-29273): Add docs release notes for w/e April 21

---

source/sync/app-builder/event-library.txt

- https://jira.mongodb.org/browse/DOCSP-29390
- [Event Library](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-29390/sync/app-builder/event-library/)

(DOCSP-29390): Sync/Event Library: Note that PBS is required

---

source/sync/app-builder/stream-data-from-client-to-atlas.txt
source/sync/app-builder/sync-data-in-atlas-with-client.txt
source/sync/app-builder/sync-data-in-client-with-atlas.txt
source/sync/data-model/create-a-schema.txt
source/sync/data-model/data-model-map.txt
source/sync/data-model/update-schema.txt
source/sync/error-handling/errors.txt

- https://jira.mongodb.org/browse/DOCSP-28152
- [Appx Docs](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-28152/)

(DOCSP-28152): Update SDK links

---

source/release-notes/backend.txt

- (DOCSP-29374) Update external change log with release notes for v20230426
- [Atlas App Services Changelog](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/release-notes-04-26-2023/release-notes/backend/)

(DOCSP-29374) Update external change log with release notes for v20230426

---

source/sync/go-to-production/compact-disk.txt

- https://jira.mongodb.org/browse/DOCSP-29315
- https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/contact-support/sync/go-to-production/compact-disk/#an-alternate-approach

(DOCSP-29315): Add public kb link and contact support note

---

.github/workflows/test-data-api.yml
examples/data-api/backend/auth/providers.json
examples/data-api/backend/functions/config.json
examples/data-api/backend/functions/endpoint/custom.js
examples/data-api/backend/functions/endpoint/hello.js
examples/data-api/backend/functions/endpoint/hello/latest.js
examples/data-api/backend/functions/endpoint/passwordRequired.js
examples/data-api/backend/functions/endpoint/sendMessage.js
examples/data-api/backend/functions/signEndpointRequest.js
examples/data-api/backend/http_endpoints/config.json
examples/data-api/bluehawk.sh
examples/data-api/custom-endpoints.sh
examples/data-api/generated-endpoints.sh
examples/data-api/utils.sh
source/data-api/custom-endpoints.txt
source/data-api/generated-endpoints.txt
source/data-api/snippets/backend/custom.snippet.custom-endpoint-function.js
source/data-api/snippets/backend/signEndpointRequest.snippet.signEndpointRequest.js
source/data-api/snippets/custom-endpoints.snippet.auth-apiKey.sh
source/data-api/snippets/custom-endpoints.snippet.auth-emailPassword.sh
source/data-api/snippets/custom-endpoints.snippet.auth-jwtTokenString.sh
source/data-api/snippets/custom-endpoints.snippet.custom-function-example.sh
source/data-api/snippets/custom-endpoints.snippet.hello-latest-ejson.sh
source/data-api/snippets/custom-endpoints.snippet.hello-latest-json.sh
source/data-api/snippets/custom-endpoints.snippet.hello.sh
source/data-api/snippets/custom-endpoints.snippet.validation-payload-signature.sh
source/data-api/snippets/custom-endpoints.snippet.validation-secret-query-param.sh

- (DOCSP-29277) Tested Custom HTTPS Endpoint examples
- [Custom Endpoints](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/test-custom-endpoints/data-api/custom-endpoints/)

(DOCSP-29277) Tested Custom HTTPS Endpoint examples

---

source/rules.txt
source/rules/expressions.txt
source/rules/roles.txt

Checked pages in the Rules section. Screenshots to be updated in https://jira.mongodb.org/browse/DOCSP-28938
- [DOCSP-28939](https://jira.mongodb.org/browse/DOCSP-28939)
- [Roles](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/rules-review/rules/roles)

(DOCSP-28939): Verify and clarify the Rules section

---

source/get-started.txt
source/tutorial/backend-examples/AlertBox.tsx
source/tutorial/backend-examples/ItemListView.snippet.addAlert.tsx
source/tutorial/backend-examples/ItemListView.snippet.alertButtonStyle.tsx
source/tutorial/backend-examples/ItemListView.snippet.alertOverlayButton.tsx
source/tutorial/backend-examples/ItemListView.snippet.alertOverlayUpdated.tsx
source/tutorial/backend-examples/ItemListView.snippet.showAlertBox.tsx
source/tutorial/backend-examples/sendAlerts.js
source/tutorial/backend.txt
source/tutorial/react-native.txt
source/tutorial/triggers-fts.txt

- https://jira.mongodb.org/browse/DOCSP-24695
- [Build an Application using Triggers and Atlas Search](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-24695/tutorial/triggers-fts/)

(DOCSP-24695): Create App Services tutorial for Triggers and Atlas Search

---

source/includes/important-stop-tiered-sync-server.rst
source/sync/app-builder/tiered-device-sync/index.txt

- https://jira.mongodb.org/browse/DOCSP-29749
- [Tiered Device Sync Guide](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-29749/sync/app-builder/tiered-device-sync/index/)

DOCSP-29749 Tiered Device Sync Feedback Fixes

---

source/sync/data-model/data-model-map.txt

- https://jira.mongodb.org/browse/DOCSP-28334
- [Data Model Mapping](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-28334/sync/data-model/data-model-map/#dictionaries)

(DOCSP-28334): Clarify a link to Kotlin SDK docs

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-29891

(DOCSP-29891): Add docs release notes for w/e May 19

---

source/tutorial/triggers-fts.txt

Updates tutorial page based on feedback from https://github.com/10gen/cloud-docs/pull/4455#pullrequestreview-1433369483
- https://jira.mongodb.org/browse/DOCSP-30027
- [Build Reverse Search Into Your Application](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-30027/tutorial/triggers-fts/)

(DOCSP-30027): Update title and intro for Triggers and Atlas Search tutorial to reflect percolator use case

---

source/tutorial/flutter.txt

- https://jira.mongodb.org/browse/DOCSP-30014
- [Flutter Tutorial](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-30014/tutorial/flutter/#add-a-new-property-to-the-model)

(DOCSP-30014) Replace deprecated flutter command

---

source/authentication.txt
source/authentication/custom-jwt-okta-config-admin-api-template.sh
source/authentication/custom-jwt-okta-config-template.json
source/authentication/firebase-jwt.txt
source/authentication/okta-jwt.txt

- (DOCSP-29896) Custom JWT + Okta
- [Okta JWT Authentication (Custom JWT)](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/okta-auth/authentication/okta-jwt/)

(DOCSP-29896) Custom JWT + Okta

---

source/rules/sync-compatibility.txt

- https://jira.mongodb.org/browse/DOCSP-30135
- https://jira.mongodb.org/browse/DOCSP-30155
- [Device-Sync Compatible Permissions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-30135/rules/sync-compatibility/#std-label-flex-sync-expansions-consideration)

(DOCSP-30135): Clarify custom user data implications and remove outdated array info

---

source/sync/app-builder/tiered-device-sync/index.txt

- https://jira.mongodb.org/browse/DOCSP-30260
- [Tiered Device Sync Guide](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-30260/sync/app-builder/tiered-device-sync/index/#complete-the-tiered-sync-configuration-details)

(DOCSP-30260): Tiered Device Sync: Update the cloudSyncServerAuth config field name

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-30204

(DOCSP-30204): Add docs release notes for w/e June 2

---

source/release-notes/backend.txt

- (DOCSP-30430) Update external change log with release notes for v20230607
- [Atlas App Services Changelog > 07 June 2023 Release](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/release-notes-06-07-2023/release-notes/backend/)

(DOCSP-30430) Update external change log with release notes for v20230607

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-30369

(DOCSP-30369): Add docs release nots for w/e June8

---

source/sync/app-builder/tiered-device-sync/index.txt

- https://jira.mongodb.org/browse/DOCS-16195
- [Tiered Device Sync](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCS-16195/sync/app-builder/tiered-device-sync/index/)

(DOCS-16195): Tiered Device Sync: Clarify template app suggestion

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-30625

(DOCSP-30625): Add docs release notes for w/e June 16

---

source/sync/migrate-sync-modes.txt

The .NET SDK now supports backend Sync mode migration.
- [Migrate Device Sync Modes](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/sync-migration-dotnet/sync/migrate-sync-modes/#requirements)

Backend Sync mode migration: .NET support

---

config/link_checker_bypass_list.json
source/activity/alerts.txt
source/apps/deploy-github.txt
source/authentication/email-password.txt
source/graphql.txt
source/includes/extracts-service-actions.yaml
source/mongodb.txt
source/mongodb/limitations-serverless-instances.rst
source/mongodb/read-preference.txt
source/mongodb/wire-protocol.txt
source/openapi-admin-v3.yaml
source/schemas/enforce-a-schema.txt
source/security.txt
source/security/network.txt
source/sync/data-model/create-a-schema.txt
source/sync/data-model/migrate-schema-partner-collection.txt
source/triggers/authentication-triggers.txt

https://jira.mongodb.org/browse/DOCSP-30825
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/borked_links/

Fix bad links

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-30806

(DOCSP-30806): Add docs release notes for w/e June 23

---

source/rules/expressions.txt

- https://jira.mongodb.org/browse/DOCSP-30915
- [Expressions](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-30915/rules/expressions/#convert-ejson-values)

(DOCSP-30915): Add %uuidToString and %stringToUuid

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-30981

DOCSP-30981 Docs release notes for w/e June 30

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-31134

(DOCSP-31134) Add docs release notes for w/e July 3

---

source/includes/important-stop-tiered-sync-server.rst
source/sync/app-builder/edge-server.txt

- https://jira.mongodb.org/browse/DOCSP-30950
- https://jira.mongodb.org/browse/DOCSP-31350
- https://jira.mongodb.org/browse/DOCSP-31351
- [Edge Server](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-30950/sync/app-builder/edge-server/)

(DOCSP-30950): Edge Server: Update documentation based on engineering updates

---

source/release-notes/backend.txt

- (DOCSP-31221) Update external change log with release notes for v20230712
- [12 July 2023 Release](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/release-notes-07-12-2023/release-notes/backend/)

(DOCSP-31221) Update external change log with release notes for v20230712

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-31226

(DOCSP-31226): Add docs release notes for w/e July 14

---

source/schemas/enforce-a-schema.txt

https://jira.mongodb.org/browse/DOCSP-31159
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-31159/schemas/enforce-a-schema/#procedure

Change the depth of TOC

---

source/rules/filters.txt

- https://jira.mongodb.org/browse/DOCSP-30820
- [Filters](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/filter-no-sync/rules/filters/#how-app-services-applies-filters)

(DOCSP-30820): Make clear that filters are not supported in Device Sync

---

source/sync/go-to-production.txt
source/sync/go-to-production/optimize-sync-atlas-usage.txt

The linked Jira ticket requests adding info to this page that doesn't really belong here, as this page is about optimizing storage. Instead, I've updated the page name to improve clarity about its topic.
- https://jira.mongodb.org/browse/DOCSP-31514
- [Optimize Sync Storage in Atlas](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-31514/sync/go-to-production/optimize-sync-atlas-usage/)

(DOCSP-31514): Rename Optimize Sync Usage page for focus on storage

---

source/apps/metadata.txt

- https://jira.mongodb.org/browse/DOCSP-30765
- [Get App Metadata](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-30765/apps/metadata/)

DOCSP-30765 Comment out find app id CLI procedure while waiting for bug fix

---

source/sync/data-model/update-schema.txt

- https://jira.mongodb.org/browse/DOCSP-31189
- [Update your Data Model](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-31189/sync/data-model/update-schema/)

DOCSP-31189 Add default value functionality to device sync docs

---

source/apps/change-deployment-models.txt
source/includes/step-deployment-region-migration-cleanup.rst

The docs below does not mention all the implications the customer needs to make before changing deployment models.
https://www.mongodb.com/docs/atlas/app-services/apps/change-deployment-models/#change-deployment-models 
In the UI it shows these things at the point which the customer goes to actually perform the change but this is too late. They need to know what to expect prior to scheduling the change on their side.
Please also see internal documentation regarding this.
- https://jira.mongodb.org/browse/DOCSP-31144
- [Change Deployment Models](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-31144/)
[REVIEWING.md](https://github.com/mongodb/docs-app-services/blob/master/REVI …

(DOCSP-31144) changing deployment model include all pre-change implications

---

source/release-notes/backend.txt

- (DOCSP-31609) Update external change log with release notes for v20230726
- [Atlas App Services Changelog](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/release-notes-07-26-2023/release-notes/backend/)

(DOCSP-31609) Update external change log with release notes for v20230726

---

source/sync/go-to-production/production-checklist.txt

- https://jira.mongodb.org/browse/DOCSP-31862
- [Device Sync Production Checklist](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-31862/sync/go-to-production/production-checklist/)

(DOCSP-31862): Device Sync: Organize Production Checklist and add new recommendations

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-31787

(DOCSP-31787): Add docs release notes for w/e August 4

---

source/includes/dev-mode-breaking-changes.rst
source/sync/configure/sync-settings.txt
source/sync/data-model/migrate-schema-partner-collection.txt
source/sync/data-model/update-schema.txt

This shouldn't be merged until the next BAAS release.
- https://jira.mongodb.org/browse/DOCSP-31628
- [Sync Settings](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-31628/sync/configure/sync-settings/#development-mode)

(DOCSP-31628) Add documentation for development mode breaking changes

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-32037

(DOCSP-32037): Add docs release notes for w/e August 11

---

source/data-api/authenticate.txt

**https://jira.mongodb.org/browse/DOCSP-31227**
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/31227/data-api/authenticate/#bearer-authentication

Add note about finding Bearer Auth errors

---

source/triggers/database-triggers.txt

https://jira.mongodb.org/browse/DOCSP-31731
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/31731/triggers/database-triggers/#database-trigger-example (App Services UI tab, below image)

Update Twilio code example to use npm

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-32199

(DOCSP-32199): Add docs release notes for w/e August 18

---

source/openapi-admin-v3.yaml

- (DOCSP-29163) App Services Admin API Auth improvements
- [Admin API](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/admin-api-refresh-token/admin/api/v3/)

(DOCSP-29163) App Services Admin API Auth improvements

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-32479

DOCSP-32479 Add docs release notes for w/e August 25

---

source/openapi-admin-v3.yaml

- https://jira.mongodb.org/browse/DOCSP-32112
- https://jira.mongodb.org/browse/DOCSP-32484
- [adminResumeTrigger](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/adminAPI/admin/api/v3/#tag/triggers/operation/adminResumeTrigger)
- [adminCreateTrigger](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/adminAPI/admin/api/v3/#tag/triggers/operation/adminCreateTrigger)

fix description of disable_token (32112) and add project paramter (32484)

---

source/release-notes/backend.txt

- (DOCSP-32472) Update external change log with release notes for v20230823
- [Atlas App Services Changelog](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/release-notes-08-23-2023/release-notes/backend/)

(DOCSP-32472) Update external change log with release notes for v20230823

---

source/triggers/database-triggers.txt

[DOCSP-32493](https://jira.mongodb.org/browse/DOCSP-32493)
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-32493/triggers/database-triggers/#configuration

Adding info about sharded clusters

---

source/users/sessions.txt

https://jira.mongodb.org/browse/DOCSP-32886
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/32886/users/sessions/#get-a-user-access-token-over-https

reformatting

---

source/examples/generated/flutter/tutorial/facets.toml
source/facets.toml
source/reference/facets.toml
source/release-notes/facets.toml
source/tutorial/facets.toml

- https://jira.mongodb.org/browse/DOCSP-32483
Hey @dacharyc!
Here's one more set of facet.toml files for your review.  Please merge if they look good to you or let me know if there's some wonkiness or you have questions.
Thank you!
Sarah

DOCSP-32483 programmatic tagging script for app services repo

---

source/sync/app-builder/edge-server.txt

- https://jira.mongodb.org/browse/DOCSP-32947
- [Configure & Connect to an Edge Server](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-32947/sync/app-builder/edge-server/#configure-the-host)

(DOCSP-32947): Edge Server typo fix

---

source/release-notes/backend.txt

- (DOCSP-32908) Update external change log with release notes for v20230906
- [Atlas App Services Changelog](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/release-notes-09-06-2023/release-notes/backend/)

(DOCSP-32908) Update external change log with release notes for v20230906

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-32890

Add docs release notes for w/e September 8

---

source/openapi-admin-v3.yaml

https://jira.mongodb.org/browse/DOCSP-32692
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-32692/admin/api/v3/#tag/sync

Update Sync endpoint to Flexible Sync info

---

source/openapi-admin-v3.yaml

Remove ``function_name`` and ``event_processors`` from example payload. Only database triggers have the ``event_processor`` parameter, so best to standardize around using ``function_id``.
- https://jira.mongodb.org/browse/DOCSP-31417
- [Admin API: Create Trigger](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-31417/admin/api/v3/#tag/triggers/operation/adminCreateTrigger)

DOCSP-31417 Correct Example with function_id for Create Trigger

---

source/openapi-admin-v3.yaml

https://jira.mongodb.org/browse/DOCSP-33148
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-33148/admin/api/v3/#tag/sync/operation/adminGetSync

Restore reponse object data for PBS

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-33012

(DOCSP-33012): Add docs release notes for w/e Sept 15

---

source/edge-server/mongodb.txt

Note for reviewer: the link in the "Connect to the Edge Server" section referring to `edge-server-install-and-configure` does not work in this PR. That is expected behavior. It refers to a ref target added in #581 . Both of these PRs will merge together, so this link will work once it's merged into the topic branch with that PR.
- https://jira.mongodb.org/browse/DOCSP-32969
- [MongoDB APIs](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-32969/edge-server/mongodb/)

(DOCSP-32969): Edge Server: MongoDB APIs

---

source/data-api.txt

@jwilliams-mongo - there was only one page to be manually tagged and it has the correct spacing & facet syntax. ;)
Please merge when you have a moment!
Thank you!
Sarah
- https://jira.mongodb.org/browse/DOCSP-27817

DOCSP-27817 manual tagging for app-services repo

---

source/activity/alerts.txt

https://jira.mongodb.org/browse/DOCSP-33178
https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-33178/activity/alerts/#default-alerts

update list of default alerts

---

source/release-notes/backend.txt

- (DOCSP-33141) Update external change log with release notes for v20230920
- [Atlas App Services Changelog > 18 September 2023 Release](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/release-notes/backend/#std-label-backend_20230918)

(DOCSP-33141) Update external change log with release notes for v20230920

---

snooty.toml

**To be merged & deployed 9/26 5:55am ET**
See https://github.com/mongodb/docs-realm/pull/3018 for Realm-side PR
- https://jira.mongodb.org/browse/DOCSP-32998
- https://preview-mongodbcbullinger.gatsbyjs.io/atlas-app-services/docsp-32998-banner-appx/

DOCSP-32998: Add Atlas Device SDK banner to App Services project

---

source/edge-server.txt

Note: the new URL will not be live until 5:30am EST ON 9/26. Do not merge until then, as this link will 404 until the new page is live.
- https://jira.mongodb.org/browse/DOCSP-32995
- [Edge Server](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-32995/edge-server/)

(DOCSP-32995): Edge Server: Update Preview CTA

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-33144

DOCSP-33144 Add docs release notes for w/e Sept 22

---

openapi-data-api-v1/components/schemas/InsertManyResponseBody.yaml
source/openapi-data-api-v1.bundled.yaml

- (DOCSP-33314) Fix Data API OpenAPI Semantic Error
- [Data API > OpenAPI](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/data-api-fix/data-api/openapi/)

(DOCSP-33314) Fix Data API OpenAPI Semantic Error

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-33266

(DOCSP-33266): Add docs release notes for w/e September 29

---

source/data-api/custom-endpoints.txt

- (DOCSP-33317) Change copy for creating a custom HTTPS endpoint
- [Custom Endpoints > Create a Custom HTTPS Endpoint](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/custom-endpoints-copy/data-api/custom-endpoints/#create-a-custom-https-endpoint)

(DOCSP-33317) Change copy for creating a custom HTTPS endpoint

---

source/functions.txt

https://jira.mongodb.org/browse/DOCSP-33293
https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/DOCSP-33293/functions/#constraints

Add max sync operations

---

source/edge-server/configure.txt

- https://jira.mongodb.org/browse/DOCSP-33400
- [Edge Server - Configure](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-33400/edge-server/configure/#upgrade-the-edge-server-version)

(DOCSP-33400): Edge Server: Add details for upgrading the Edge Server

---

source/release-notes/backend.txt

- (DOCSP-33441) Update external change log with release notes for v20231004
- [Atlas App Services Changelog](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/release-notes-10-04-2023/release-notes/backend/)

(DOCSP-33441) Update external change log with release notes for v20231004

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-33240

DOCSP-33240 Add docs release notes for w/e October 6

---

source/triggers.txt
source/triggers/database-triggers.txt

https://jira.mongodb.org/browse/DOCSP-33333
https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/docsp-33333/triggers/database-triggers/#std-label-triggers-maximum-throughput

Add new Advanced Setting for Throughput Limits

---

source/triggers/database-triggers.txt

https://jira.mongodb.org/browse/DOCSP-33655
https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/docsp-33655/triggers/database-triggers/#configuration (end of this section)

add note about disabling event ordering

---

source/openapi-admin-v3.yaml

https://jira.mongodb.org/browse/DOCSP-33598
https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/docsp-33598/admin/api/v3/#tag/triggers/operation/adminCreateTrigger
https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/docsp-33598/admin/api/v3/#tag/triggers/operation/adminGetTrigger

add maximum_throughput to admin API (create and get trigger)

---

source/openapi-admin-v3.yaml
source/release-notes/backend.txt

https://jira.mongodb.org/browse/DOCSP-33421
https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/yaml_test/admin/api/v3/#tag/services/operation/adminListServices
The scope of this ticket expanded to including a new endpoint and updating the response objects for several endpoints.

Add adminListServices endpoint

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-33533

DOCSP-33533 Add docs release notes for w/e October 13

---

source/schemas/types.txt

https://jira.mongodb.org/browse/DOCSP-33226
https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/DOCSP-33226/schemas/types/#geospatial-data

add geopoint

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-33716

DOCSP-33716 Add docs release notes for w/e October 20

---

source/release-notes/backend.txt

- (DOCSP-33725) Update external change log with release notes for v20231018
- [Atlas App Services Changelog > 18 October 2023 Release](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/release-notes-10-18-2023/release-notes/backend/)

(DOCSP-33725) Update external change log with release notes for v20231018

---

source/security/private-endpoints.txt

https://jira.mongodb.org/browse/DOCSP-33805
https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/docsp-33805/security/private-endpoints/#private-endpoint-limitations

add note about inbound-only use of private endpoints

---

source/openapi-admin-v3.yaml
source/security/private-endpoints.txt

https://jira.mongodb.org/browse/DOCSP-33237
- https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/docsp-33237/security/private-endpoints/
https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/docsp-33237/admin/api/v3/#tag/security/operation/allNonVpcClientRequests

Add new UI and API for Toggling Endpoint Access

---

source/includes/app-services-cli-overview.rst

- (DOCSP-33281) CLI Profiles
- [App Services CLI > CLI Profiles](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/cli-profile/cli/#std-label-cli-profiles)

(DOCSP-33281) CLI Profiles

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-33933

(DOCSP-33933): Add docs release notes for w/e Nov 3

---

source/release-notes/backend.txt

- (DOCSP-33930) Update external change log with release notes for v20231101
- [Atlas App Services Changelog > 01 November 2023 Release](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/release-notes-11-01-2023/release-notes/backend/)

(DOCSP-33930) External release notes for v20231101

---

source/functions/mongodb/write.txt

- https://jira.mongodb.org/browse/DOCSP-33928
- [Write (Functions)](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-33928/functions/mongodb/write/#array-update-operators)

DOCSP-33928 Fix Update Array Example

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-34097

(DOCSP-34097): Add docs release notes for w/e November 10

---

source/release-notes/backend.txt

- (DOCSP-34368) External release notes for v20231115
- [Atlas App Services Changelog > 15 November 2023 Release](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/release-notes-11-15-2023/release-notes/backend/#std-label-backend_20231115)

(DOCSP-34368) External release notes for v20231115

---

docs-release-notes.md

- https://jira.mongodb.org/browse/DOCSP-34366

DOCSP-34366 Add docs release notes for w/e November 17

---

source/reference/service-limitations.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34584
- [Service Limitations](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-34584/reference/service-limitations/#request-traffic)
- Reference/Service Limitations: Add reasoning for request traffic limitations and ensure that app services can handle more requests than the set limits.

DOCSP-34584 Reasoning for request traffic limitations

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34625

DOCSP-34625 Add docs release notes for w/e December 1

---

source/sync/configure/sync-settings.txt

No ticket for this. I just noticed it was missing as I was working on updating asymmetric object details in the SDK docs repo.
(There is currently a Snooty build issue that is preventing staging builds, so there's no staged version of this page to review.)
- Configure Sync/Sync Settings: Add Flutter SDK to the list of SDKs that support Data Ingest.

Sync/Data Ingest: Add Flutter SDK to SDKs that support Data Ingest

---

source/release-notes/backend.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34635
- [Atlas App Services Changelog > 29 November 2023 Release](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-34635/release-notes/backend/#29-november-2023-release)

DOCSP-34635 External release notes for v20231129

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34725

(DOCSP-34725): Add docs release notes for w/e Dec 8

---

source/openapi-admin-v3.yaml

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34871
- [App Services Admin API](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-34871/admin/api/v3/#tag/endpoints/operation/adminCreateEndpoint): Endpoints/Create, Endpoints/Modify, Data API/Enable, Data API/Modify: update the broken links
- genre
- **Reference**
- App Services Admin API: Fix broken links in Endpoints/Create, Endpoints/Modify, Data API/Enable, Data API/Modify.

(DOCSP-34871): Fix broken links

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34893

DOCSP-34893 Add docs release notes for w/e December 15

---

source/schemas/types.txt

NOTE: This PR depends on https://github.com/mongodb/docs-realm/pull/3116/ - the ref won't exist in prod until that gets merged and published.
Jira ticket: https://jira.mongodb.org/browse/DOCSP-34471
- [Schema Types](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-34471/schemas/types/#querying): Add Flutter to the list of SDKs that support geospatial data. Alphabetize list. 
- genre
- **Define a Data Model**
- Schemas/Schema Types: Add Flutter SDK to the list of SDKs that support geospatial data.

(DOCSP-34471): Schemas: Add Flutter to the list of SDKs that support geospatial data

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35231

(DOCSP-35231): Add docs release notes for w/e January 5

---

source/domain-migration.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35267
- [Domain Migration](https://preview-mongodbkrollinsmdb.gatsbyjs.io/atlas-app-services/DOCSP-35267/domain-migration/): new orphan page
This PR adds a new orphan page that the Atlas UI can link to for more information about the upcoming base URL migration. I didn't add any tags to this new page, as we don't necessarily want it to be discoverable. This is part of an announcement strategy - no changes have been made to the SDKs yet.
When the SDKs are actually updated, we can address the URL change for each SDK.
- genre
- Domain Migration: Add new page that contains information about the upcoming base URL changes. …

(DOCSP-35267): Add domain migration page

---

source/sync/configure/sync-settings.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-33945
- [Sync Settings](https://preview-mongodbkrollinsmdb.gatsbyjs.io/atlas-app-services/DOCSP-33945/sync/configure/sync-settings/#breaking-changes): Update dev mode breaking changes section to mention support can enable the feature for older Apps and add more SDK versions
- genre
- **Device Sync/Configure Sync**
- Sync Settings: Update dev mode breaking changes section to mention support can enable the feature for older Apps and add more SDK versions

(DOCSP-33945) Update dev mode breaking changes section

---

snooty.toml
source/domain-migration.txt
source/openapi-admin-v3.yaml
source/release-notes/backend.txt
source/users/sessions.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35368
- [Release Notes](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-35368/release-notes/backend/#10-january-2024-release): Add release notes for v20240110.
- [Manage User Sessions](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-35368/users/sessions/#configure-refresh-token-expiration): Update user session expiration details to specify minimum and maximum expiration times.
- Admin API
- [Refresh an Admin API Session Access Token](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-35368/admin/api/v3/#section/Refresh-an-Admin-API-Session-Access-Token): Mention default, min, and max refresh token time periods.
- [Refresh Token Expiration Endpoints (GET, …

(DOCSP-35368): External release notes for v20240110

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35339

(DOCSP-35339): Add docs release notes for w/e January 12

---

source/release-notes/backend.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35769
- [Release Notes](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-35769/release-notes/backend/): Add release notes for v20240124.
Release Notes: Add release notes for v20240124.

DOCSP-35769 External release notes for v20240124

---

source/edge-server/configure.txt
source/edge-server/connect.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35915
- [Configure Edge Server](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-35915/edge-server/configure/#complete-the-edge-server-configuration-details): Update the config object and field information. Add a section about running `make` to generate an edge_config.json so you can set the `baseURL` and other details.
- [Connect to Edge Server](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-35915/edge-server/connect/): Update instructions to connect to the Edge Server to refer to `baseURL` instead of `hostname`.
- genre
- Configure Edge Server: Update the config …

(DOCSP-35915): Edge Server: Update configuration details

---

source/sync/migrate-sync-modes.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-36154
- [Migrate Device Sync Modes](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-36154/sync/migrate-sync-modes/): Remove duplicate sentence.
- genre
- Migrate Device Sync Modes: Remove duplicate sentence.

(DOCSP-36154): Remove duplicate sentence

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35996

(DOCSP-35996): Add docs release notes for w/e Feb 2

---

source/release-notes/backend.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-36320
- [Release Notes](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-36320/release-notes/backend/#7-february-2024-release): change log for week of feb 7

DOCSP-36320 External release notes for v20240207

---

snooty.toml
source/apps/deploy-github.txt
source/cli.txt
source/cli/appservices-deploy-configure.txt
source/cli/appservices-deploy-describe.txt
source/cli/appservices-deploy-disable.txt
source/cli/appservices-deploy-enable.txt
source/cli/appservices-deploy.txt

Jira tickets: 
- https://jira.mongodb.org/browse/DOCSP-36281
- https://jira.mongodb.org/browse/DOCSP-35432
- https://jira.mongodb.org/browse/DOCSP-35672
Updated page:
- [Deploy Automatically with GitHub](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-36281/apps/deploy-github/): Add tabs for CLI and API procedures, update details about making changes from the CLI.
New pages (autogenerated from CLI docs):
- [appservices deploy](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-36281/cli/appservices-deploy/)
- [appservices deploy configure](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-36281/cli/appservices-deploy-configure/)
- [appservices deploy describe](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-3628 …

(DOCSP-36281): Add new appservices deploy CLI docs

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-36317

DOCSP-36317 Add docs release notes for w/e Feb 9

---

source/billing.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-36195
- [Billing](https://preview-mongodbcbullinger.gatsbyjs.io/atlas-app-services/docsp-36195-eventbridge-billing/billing/#app-services-requests): Update Function Executions section to include the new custom error function.
- genre
- **Reference**
- Data Access Role Examples: Update App Services Requests section to include the new custom error function as an example of a Function Execution billing. 

DOCSP-36195: Update Billing page with custom error function info

---

source/openapi-admin-v3.yaml

Jira ticket: https://jira.mongodb.org/browse/DOCSP-36193
- [App Services Admin API](https://preview-mongodbcbullinger.gatsbyjs.io/atlas-app-services/docsp-36194-eventbridge-admin-api/admin/api/v3/#tag/triggers)  (reference page): Add new `error_handler` object to the Database Trigger type for all relevant Trigger endpoints.
- [ **N/A** ] Did you tag pages appropriately? 
- genre
- **Reference**
- App Services Admin API: Update page to support AWS EventBridge custom error handling feature by adding the new `error_handler` object property to Database type Trigger payloads in all relevant Trigger endpoints. 
[REVIEWING.md](https://github.com/mongodb/docs-app-services/blob/master/ …

DOCSP-36193: Update Admin API Trigger endpoints with EventBridge error handler properties

---

source/reference/config/triggers.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-36192
- [Trigger Configuration](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-36192/reference/config/triggers/): Update database trigger and add event processor and error handler config.
- genre
**Reference**
- App Configuration files/ Triggers: Update database trigger config, most importantly adding ``event_processors`` and ``error_handler`` config.

DOCSP-36192 Update Trigger Config for EventBridge Error Handling

---

source/sync/configure/sync-settings.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-36938
- [PAGE_NAME](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/BRANCH_NAME/): description of changes
- genre
**Device Sync**
- Configure Sync/Sync Settings: Fix small typo.

(DOCSP-36938) Fixes typo.

---

source/functions.txt

- [Functions Landing Page](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/customer-resolvers-typo-fix/functions/): Fix typo.
- genre
- **Functions**
- Landing Page: Fix typo.

Functions: Fix 'customer' resolvers typo

---

source/functions/test.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-37063
- [Test Atlas Functions](https://preview-mongodbjwilliamsmongo.gatsbyjs.io/atlas-app-services/DOCSP-37063/functions/test/#export-function-for-use-in-unit-tests): corrected typo based on feedback from folks at Smartling

DOCSP-37063: typo fix for translation project

---

source/openapi-admin-v3.yaml

Some of the operation responses are not compatible with the Swift OpenAPI generator.
This PR fixes the syntax of a few operation responses.
- **Fix operation responses**
- Fixes the syntax of a few operation responses

Fix OpenAPI responses syntax

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-37028

DOCSP-37028 Add docs release notes for w/e Feb 23

---

source/users/read-metadata.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34653
- [Read User Metadata](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-34653/users/read-metadata/#view-user-data): Update procedure wording to match UI changes.
- genre
- **Authenticate & Manage Users**
- Read User Metadata: Update procedure wording to match UI changes.

(DOCSP-34653): Read User Metadata: Update procedure wording to match UI changes

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-37205

(DOCSP-37205): Add docs release notes for w/e March 1

---

source/triggers.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34560
- [Triggers landing page](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-34560/triggers/#diagnose-duplicate-events): Add a section about diagnosing duplicate events.
- genre
- **Triggers**
- Landing Page: Add a section about diagnosing duplicate events.

(DOCSP-34560): Add information about duplicate Trigger events

---

source/functions/mongodb/api.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-35722
- [MongoDB API Reference](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-35722/functions/mongodb/api/#collection.findone--): Add note about using find() and sort() together. 
- genre
**Functions**
- MongoDB API Reference: Add note with example on finding one document in a sorted collection using find(), sort(), and next(). 

DOCSP-35722 Workaround for using find() and sort() together

---

source/openapi-admin-v3.yaml

Jira ticket: https://jira.mongodb.org/browse/DOCSP-37383
- [Admin API](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-37383/admin/api/v3/#tag/services/operation/adminLinkMultiDataSources): Added new "Link multiple data sources" endpoint. 
- genre
**References**
- App Services Admin API: Added new "Link multiple data sources" endpoint. 

DOCSP-37383 New endpoint for linking multi-data sources

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-37406

DOCSP-37406 Add docs release notes for w/e March 8

---

source/index.txt
source/introduction.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-33983
- [Landing page](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-33983/): Change "Realm SDKs" entry in sidebar to "Atlas Device SDK." Update naming throughout landing page.
- [Introduction](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-33983/introduction/): Update naming and positioning throughout landing page.
- genre
- Landing page: Change "Realm SDKs" entry in sidebar to "Atlas Device SDK." Update naming throughout landing page.
- Introduction: Update Realm naming and positioning throughout landing page.
[REVIEWING.md](https://github.com/mongodb/docs-app-services/blob/master …

Update high-level pages for Device SDK positioning

---

source/cli/appservices-schema-generate.txt
source/cli/appservices-schema-validate.txt
source/cli/appservices-users-count.txt
source/cli/appservices-users.txt

Reverts mongodb/docs-app-services#707

Revert "Undo CLI release for users count, schema validate, and schema generate"

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-37644

(DOCSP-37644): Add docs release notes for w/e March 15

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38056

DOCSP-38056: Add docs release notes for w/e March 29

---

source/graphql/migrate-wundergraph.txt

Tiny fix for a recently added page.

Fix incorrectly-formatted hyperlink

---

source/apps/create.txt
source/includes/mongodb-4.4-required-for-sync-admonition.rst
source/includes/mongodb-5.0-required-for-sync-admonition.rst

Jira ticket: https://jira.mongodb.org/browse/DOCSP-34971
- [Create an App](https://preview-mongodbcbullinger.gatsbyjs.io/atlas-app-services/docsp-34971-mongodb-version/apps/create/#:~:text=MongoDB%20Version%205.0%20or%20Higher%20Required)
- genre
- **Develop & Deploy Apps**
- Create an App: Update the noted minimum MongoDB version from v4.4 to v5.0.

DOCSP-34971: Update minimum MongoDB version to v5.

---

source/triggers/scheduled-triggers.txt
source/tutorial/flutter.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-37311
- [Flutter Tutorial](https://preview-mongodbcbullinger.gatsbyjs.io/atlas-app-services/docsp-37311-tutorial-updates/tutorial/flutter/#:~:text=lib/realm/schemas.realm.dart)
- genre
- **Get Started**
- Device Sync Tutorial - Flutter: Rename `lib/realm/schemas.g.dart` to `lib/realm/schemas.realm.dart` to reflect the new file extension generated in the upgraded Flutter Template App

DOCSP-37311: Update Flutter tutorial for v2 app

---

source/release-notes/backend.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38165
- [release notes](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-38165/release-notes/backend/)
- genre
**Release Notes**
- Update external changelog with release notes for sorted apps in the App Services UI and a data source's service name now defaulting to the cluster name. 

DOCSP-38165 External release notes for v20240403

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38157

DOCSP-38157 Add docs release notes for w/e April 5

---

source/users/custom-metadata.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38031
- [Define User Metadata](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-38031/users/custom-metadata/#custom-user-data): add notes about changes due to user metadata caching
- genre
**Authenticate and Manage Users**
- Define User Metadata: Add notes for updates to handling authentication user metadata.

DOCSP-38031 Updates to Authentication Provider Metadata

---

source/data-api.txt
source/functions.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-37883
- [Data API](https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/DOCSP-37883/data-api/#constraints)
- [Functions](https://preview-mongodbmongocaleb.gatsbyjs.io/atlas-app-services/DOCSP-37883/functions/#constraints)
- genre

Add Constraints section to Data API and update Function size limit

---

source/edge-server/mongodb.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38562
- [Edge Server MongoDB API Support](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-38562/edge-server/mongodb/#update): Add `findAndModify` command to `update` options.
- genre
- Edge Server MongoDB API Support: Add `findAndModify` command to `update` options.

Edge Server: Add findAndModify command

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38396

DOCSP-38396: Release notes w/e April 12

---

source/openapi-admin-v3.yaml

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38290
- [Create a VPC private endpoint](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-38290/admin/api/v3/#tag/security/operation/adminCreatePrivateEndpoint): create private endpoint
- [List VPC Private Endpoint Services](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-38290/admin/api/v3/#tag/security/operation/adminListPrivateEndpointServices): list VPC private endpoint services
- [Modify a VPC private endpoint](https://docs-atlas-staging.mongodb.com/atlas-app-services/docsworker-xlarge/DOCSP-38290/admin/api/v3/#tag/security/operation/adminUpdatePrivateEndpoint): modify a VPC private endpoint
- genre
- …

DOCSP-38290 Update Admin API private endpoint references

---

source/release-notes/backend.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38688
- [release notes](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-38688/release-notes/backend/#17-april-2024-release)
- genre
**Reference**
- Release Notes: Update external changelog with release notes for new schema version selector, the ``service.cloud.mongodb.com`` domain change, and more.

DOCSP-38688 External release notes for v20240417

---

source/edge-server.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38550
- [Atlas Edge Server](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-38550/edge-server/): Update details for Public Preview. Add info about using MongoDB Drivers and tools. Remove verbiage or clarify behavior that is Atlas Device SDK-specific.
The todos below won't be resolved in this PR, and will carry over to the feature branch for resolution prior to merging the docs.
TODOs for Feature Branch
- genre
- Landing Page: Update details for Public Preview. Add info about using MongoDB Drivers and tools. Remove verbiage or clarify behavior that is Atlas Device SDK-specific. …

(DOCSP-38550): Update Edge Server landing page for Public Preview

---

snooty.toml
source/edge-server/connect.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38553
- [Connect to an Edge Server](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-38553/edge-server/connect/): Update the page for the Public Preview. Add details about:
- Roaming with Atlas Device SDK
- Connecting via the wireprotocol with authentication
- Connecting via Compass
Note: There is currently a placeholder in the "Connect with Compass" section, as I do not know what URI to use to connect with Compass. I'll update this section when I get the info from engineering, or when I can test it myself.
- genre
- Connect to an Edge Server: Update the page for the Public Preview. Add …

(DOCSP-38553): Update the 'Connect' page for Public Preview

---

source/cli/appservices-function-list.txt
source/cli/appservices-function-run.txt
source/cli/appservices-function.txt
source/cli/appservices-schema-generate.txt
source/cli/appservices-schema-validate.txt
source/cli/appservices-schema.txt
source/cli/appservices-users-count.txt
source/cli/appservices-users-list.txt
source/cli/appservices-users.txt

Jira ticket: 
- https://jira.mongodb.org/browse/DOCSP-38465
- https://jira.mongodb.org/browse/DOCSP-38288
- https://jira.mongodb.org/browse/DOCSP-38418 
Staging links:
[users list](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-38465/cli/appservices-users-list/)
[functions run](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-38465/cli/appservices-function-run/)
[functions list](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-38465/cli/appservices-function-list/)
- genre
**Reference**
- App Services CLI: Update cli reference for the `--use-local-app` flag addition to the `function run` command, the …

DOCSP-38465 Funtion run and users list CLI updates

---

source/edge-server/configure.txt
source/includes/edge/edgectl-config-flags.rst
source/includes/edge/edgectl-init-flags.rst

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39016
- [Configure an Edge Server Instance](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-39016/edge-server/configure/)
- genre

(DOCSP-39016): Update `edgectl` details for `init`, `query` and `profile`

---

source/edge-server.txt
source/edge-server/manage-edge-servers.txt
source/edge-server/monitor.txt
source/edge-server/permissions.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38863
- [Manage Edge Servers](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-38863/edge-server/manage-edge-servers/)
- Add info about adding Edge Servers to a Device Sync App.
- Populate Admin API details in procedures.
- Populate placeholder refs to Metrics and Logs.
- Note that you must stop and start an Edge Server instance after adding a new collection, per [this review comment on the feature branch](https://github.com/mongodb/docs-app-services/pull/727#discussion_r1579744135).
- [Permissions Guide](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-38863/edge-server/permissions/): Fix title underline too short build warnings, and populate Admin API endpoint placeholder.
- [Monitor Edge …

(DOCSP-38863): Address TODOs and placeholders to prepare Feature Branch for merging

---

source/release-notes/backend.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38878
- [release notes](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-38878/release-notes/backend/)
- genre
**Reference**
- Release Notes: Update external changelog with release notes for App Services CLI updates. 

DOCSP-38878 External release notes for v20240424

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38871

DOCSP-38871 Add docs release notes for w/e April 26

---

source/billing.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38559
- [Billing](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-38559/billing/#atlas-edge-server): New "Atlas Edge Server" section with a high-level blurb about billing.
- genre
- **Reference**
- Billing: New "Atlas Edge Server" section with a high-level blurb about billing.

(DOCSP-38559): Add billing details for Edge Server

---

source/edge-server/configure.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39155
- [Configure Edge Server](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-39155/edge-server/configure/#run-multiple-edge-server-instances-on-a-host): Add information about managing `edgectl` profiles with the various `profile` commands.
- genre
- Configure Edge Server: Add information about managing `edgectl` profiles with the various `profile` commands.

(DOCSP-39155): Add details about edgectl profile management

---

source/edge-server/configure.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39172
- [Configure Edge Server](https://preview-mongodbdacharyc.gatsbyjs.io/atlas-app-services/DOCSP-39172/edge-server/configure/#simulate-offline-connectivity): New "Simulate Offline Connectivity" section describing how to use offline demo mode.
- genre
- Configure Edge Server: New "Simulate Offline Connectivity" section describing how to use offline demo mode.

(DOCSP-39172): Edge Server: Add details about offline demo mode

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39069

DOCSP-39069: Add docs release notes for w/e May 3

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39238

(DOCSP-39238): Add docs release notes for w/e May 10

---

source/release-notes/backend.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39275
- [release notes](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-39275/release-notes/backend/)
- genre
**Reference**
- Release Notes: Update external changelog with release notes for new App Services CLI platform support for Linux Arm64 machines.

DOCSP-39275 External release notes for v20240508

---

examples/functions/functions_tester/functions/package-lock.json
examples/functions/functions_tester/functions/package.json
examples/functions/functions_tester/package-lock.json
examples/functions/functions_tester/package.json
examples/functions/functions_tester/test/integration/retryHandlers.test.js
openapi-data-api-v1/package-lock.json
openapi-data-api-v1/package.json

Update Data API and Functions test suite dependencies to resolve security alerts. Fix failing tests.

Update Data API and Functions test suite dependencies

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39461

(DOCSP-39461): Add docs release notes for w/e May 17

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39647

DOCSP-39647 Add docs release notes for w/e May 24

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-40112

Add docs release notes for w/e June 7

---

source/includes/note-collections-in-mixed-sync.rst
source/release-notes/backend.txt
source/sync/data-model/data-model-map.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-40119
- [Release Notes](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-40119/release-notes/backend/): description of changes
- genre
**Release Notes**
- Update external changelog with release notes for Atlas Events, updated Function Editor, Collections in Mixed, and more.

DOCSP-40119 Add docs release notes for v20240605

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-40330

DOCSP-40330 Add docs release notes for w/e June 14

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-40552

(DOCSP-40552): Docs release notes for w/e June 21

---

source/billing.txt
source/introduction.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-38905
- [Billing](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-38905/billing/): Add information about new daily free tier limits and tier pricing for requests.
- genre
**Reference**
- Billing: Updated page with new billing practice, including new daily free tier limits.

DOCSP-38905 Billing Migration and Modernization

---

source/users/custom-metadata.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-41040
- [Define Custom User Metadata](https://preview-mongodbcbullinger.gatsbyjs.io/atlas-app-services/docsp-41040-typo-fix/users/custom-metadata/#:~:text=reference%20an%20existing%20function): Fix typo
- genre
- [N/A] Create a Jira ticket for related docs-realm work, if any
- **Authenticate & Manage Users**
- Define User Metadata: Fix typo and update references to "Realm" to "Atlas Device SDK." 

DOCSP-41040: Fix typo on Custom Metadata page

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-40768

DOCSP-40768 Docs release notes for w/e June 28

---

source/reference/service-limitations.txt
source/release-notes/backend.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-40846
- [Release Notes](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-40846/release-notes/backend/)
- genre
**Release Notes**
- Update external changelog with release notes for the CLI, Edge Server, Atlas Events, and more.

DOCSP-40846 Add docs release notes for v20240646

---

source/billing.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-40176
- [Billing](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-41076/billing/#free-tier-thresholds)
- genre
**Reference**
- Billing: Update formatting of free tier thresholds to represent independent threshold model. 

DOCSP-41076 Update formating for free tier thresholds

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-41048

DOCSP-41048: Add release notes for w/e July 5

---

source/reference/partition-based-sync.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-39239
- [PBS](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-39239/reference/partition-based-sync/): Added link to migration guide. 
- genre
**Reference**
- Partition-Based Sync Mode: Added a link to the migration guide from PBS to Flexible Sync. 

DOCSP-39239 Recommend PBS migration

---

source/users/custom-metadata.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-41393
- [Define User Metadata](https://preview-mongodbosharafmdb.gatsbyjs.io/atlas-app-services/DOCSP-41393/users/custom-metadata/#user-creation-function): fixed a typo
- [N/A] Did you tag pages appropriately?
- genre
- [N/A] Create a Jira ticket for related docs-realm work, if any
- **Authenticate & Manage Users**
- Define User Metadata: Fix a typo under "User Creation Function".

DOCSP-41393: fixed typo

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-41236

(DOCSP-41236): Add docs release notes for w/e July 12

---

source/release-notes/backend.txt
source/sync/data-model/update-schema.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-41243
- [Release Notes](https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-41243/release-notes/backend/)
- genre
Release Notes
- Update external changelog with release notes for a variety of App Services UI changes and bug fixes. 

DOCSP-41243 Add docs release notes for v20240710

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-41669No pages to previewNo pages to preview

DOCSP-41669 Release Notes week ending 7/26

---

source/release-notes/backend.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-41689
- [Release Notes](https://preview-mongodbosharafmdb.gatsbyjs.io/atlas-app-services/DOCSP-41689-external-BAAS-release-notes/release-notes/backend/)
- genre
Release Notes
- Update external changelog with release notes for a variety of bug fixes and App Services changes related to the deprecation of GraphQL and Static Hosting. 
<br/> - https://deploy-preview-815--app-services.netlify.app/release-notes/backend<br/> - https://deploy-preview-815--app-services.netlify.app/release-notes/backend<br/> - …

DOCSP-41689 BaaS Release Notes v20240724

---

source/edge-server.txt
source/edge-server/configure.txt
source/edge-server/connect.txt
source/edge-server/manage-edge-servers.txt
source/edge-server/mongodb.txt
source/edge-server/monitor.txt
source/edge-server/permissions.txt
source/index.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-42011
<br/> - https://deploy-preview-819--app-services.netlify.app/edge-server<br/> - https://deploy-preview-819--app-services.netlify.app/edge-server/configure<br/> - https://deploy-preview-819--app-services.netlify.app/edge-server/connect<br/> - https://deploy-preview-819--app-services.netlify.app/edge-server/manage-edge-servers<br/> - https://deploy-preview-819--app-services.netlify.app/edge-server/mongodb<br/> - https://deploy-preview-819--app-services.netlify.app/edge-server/monitor<br/> - https://deploy-preview-819--app-services.netlify.app/edge-server/permissions<br/> - https://deploy-preview-819--app-services.netlify.app/index
- genre
- …

(DOCSP-42011) Emphasize that Edge Server is in preview

---

.github/workflows/add-netlify-links.yml
docs-release-notes.md

Jira ticket: [DOCSP-41871](https://jira.mongodb.org/browse/DOCSP-41871)
https://github.com/MongoCaleb/docs-app-services/blob/release_notes/docs-release-notes.md

Release notes for 8/3/2024

---

source/release-notes/backend.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-42170
I only included a few bug fixes. The rest of the items seem to be internal implementation details. Though maybe we want to mention the CLI not showing some graphql/hosting fields in output? I'm split on whether that info should be included here or not.
<li><a href=https://deploy-preview-823--app-services.netlify.app/release-notes/backend>release-notes/backend</a></li>
- [Atlas App Services Changelog](https://deploy-preview-823--app-services.netlify.app/release-notes/backend/)
- genre
- Update external changelog with release notes for several bug fixes.
[REVIEWING.md](https://github.com/mongodb/docs-app-services/blob/mast …

(DOCSP-42170) BAAS release notes for 20240807

---

source/tutorial/backend.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-36699
<li><a href=https://deploy-preview-824--app-services.netlify.app/tutorial/backend>tutorial/backend</a></li>
- genre
- **Tutorial**
- GitHub webhook integration tutorial was missing the fact that the secret needs to be appended to the URL, **not** sent as a GitHub secret in the body. 

Clarify steps to send a secret to the endpoint

---

source/functions.txt

Jira ticket: https://jira.mongodb.org/browse/DOCS-16746
- [Function](https://preview-mongodbosharafmdb.gatsbyjs.io/atlas-app-services/DOCS-16746/functions/#how-to-write-a-function): fixed a typo
- genre
- **Functions**
- Fix a typo.

DOCS-16746: Fized typo

---

docs-release-notes.md

Jira ticket: https://jira.mongodb.org/browse/DOCSP-42128

(DOCSP-42128) Release notes week ending 8/09

---

source/functions.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-41897
<li><a href=https://deploy-preview-829--app-services.netlify.app/functions>functions</a></li>
- genre
- **Functions**
- Landing page: Fix incorrect option name in code examples (`--function` to `--name`).

(DOCSP-41897): Functions: Fix incorrect option name in example

---

snooty.toml

* Build Log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66c201bd8e811ae672e6d15e
* Staging: https://preview-mongodbi80and.gatsbyjs.io/atlas-app-services/fix-realm-intersphinx-url/schemas/types/#counter

DOP-4936: Update intersphinx URL for realm

---

source/release-notes/backend.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-42782
- https://preview-mongodblindseymoore.gatsbyjs.io/atlas-app-services/DOCSP-42782/release-notes/backend/
- genre

DOCSP-42782 Docs release notes for v20240821

---

snooty.toml
source/deprecation.txt
source/sync/device-sync-deprecation.txt

<li><a href=https://deploy-preview-845--app-services.netlify.app/deprecation>deprecation</a></li><li><a href=https://deploy-preview-845--app-services.netlify.app/sync/device-sync-deprecation>sync/device-sync-deprecation</a></li>
- genre

Several small depreaction updates

---

README.md
source/data-api/data-api-deprecation.txt
source/deprecation.txt
source/functions/test.txt
source/introduction.txt
source/sync/device-sync-deprecation.txt

<li><a href=https://deploy-preview-846--app-services.netlify.app/data-api/data-api-deprecation>data-api/data-api-deprecation</a></li><li><a href=https://deploy-preview-846--app-services.netlify.app/deprecation>deprecation</a></li><li><a href=https://deploy-preview-846--app-services.netlify.app/functions/test>functions/test</a></li><li><a href=https://deploy-preview-846--app-services.netlify.app/introduction>introduction</a></li><li><a href=https://deploy-preview-846--app-services.netlify.app/sync/device-sync-deprecation>sync/device-sync-deprecation</a></li>
- genre …

Add Device Sync alternatives

---

source/sync/device-sync-deprecation.txt

<li><a href=https://deploy-preview-847--app-services.netlify.app/sync/device-sync-deprecation>sync/device-sync-deprecation</a></li>
- genre

Move ditto up

---

source/triggers.txt
source/triggers/authentication-triggers.txt
source/triggers/aws-eventbridge.txt
source/triggers/database-triggers.txt
source/triggers/disable.txt
source/triggers/scheduled-triggers.txt

<li><a href=https://deploy-preview-848--app-services.netlify.app/triggers>triggers</a></li><li><a href=https://deploy-preview-848--app-services.netlify.app/triggers/authentication-triggers>triggers/authentication-triggers</a></li><li><a href=https://deploy-preview-848--app-services.netlify.app/triggers/aws-eventbridge>triggers/aws-eventbridge</a></li><li><a href=https://deploy-preview-848--app-services.netlify.app/triggers/database-triggers>triggers/database-triggers</a></li><li><a href=https://deploy-preview-848--app-services.netlify.app/triggers/disable>triggers/disable</a></li><li><a href=https://deploy-preview-848--app-services.netlify.app/triggers/scheduled-triggers>triggers/scheduled-triggers</a></li>
Before merging your PR, …

Remove meta tag from triggers pages

---

source/sync/device-sync-deprecation.txt

<li><a href=https://deploy-preview-850--app-services.netlify.app/sync/device-sync-deprecation>sync/device-sync-deprecation</a></li>
- genre

Add link to Ditto migration guide

---

source/sync/device-sync-deprecation.txt

<li><a href=https://deploy-preview-851--app-services.netlify.app/sync/device-sync-deprecation>sync/device-sync-deprecation</a></li>
- genre

Add PowerSync blurb and migration guide link

---

source/sync/device-sync-deprecation.txt

<li><a href=https://deploy-preview-853--app-services.netlify.app/sync/device-sync-deprecation>sync/device-sync-deprecation</a></li>
- genre

Add ObjectBox to Device Sync deprecation page

---

source/logs/function.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-43630
<li><a href=https://deploy-preview-854--app-services.netlify.app/logs/function>logs/function</a></li>
- genre
- **Monitor App Activity**
- Log Types > Function Logs: Correct ``Logs`` field description.

DOCSP-43630: Correct wording in Function Log description

---

source/sync/device-sync-deprecation.txt

Jira: 
https://jira.mongodb.org/browse/DOCSP-44013
Slack: 
https://mongodb.slack.com/archives/C07PM87M9LM/p1727757243715769?thread_ts=1727734784.268629&cid=C07PM87M9LM
<li><a href=https://deploy-preview-859--app-services.netlify.app/sync/device-sync-deprecation>sync/device-sync-deprecation</a></li>

update cdn links

---

source/graphql.txt
source/graphql/migrate-render.txt
source/hosting.txt
source/hosting/migrate-render.txt
source/migrate-hosting-graphql.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-44572
<li><a href=https://deploy-preview-869--app-services.netlify.app/graphql/migrate-render>graphql/migrate-render</a></li><li><a href=https://deploy-preview-869--app-services.netlify.app/hosting/migrate-render>hosting/migrate-render</a></li><li><a href=https://deploy-preview-869--app-services.netlify.app/graphql>graphql</a></li><li><a href=https://deploy-preview-869--app-services.netlify.app/hosting>hosting</a></li><li><a href=https://deploy-preview-869--app-services.netlify.app/migrate-hosting-graphql>migrate-hosting-graphql</a></li>
- genre
[REVIEWING.md](https://github.com/mongodb/docs-app-services/blob/master/REVIEWING. …

(DOCSP-44572) Add Render as migration option

---

config/redirects
source/data-api.txt
source/data-api/examples.txt

Jira ticket: https://jira.mongodb.org/browse/DOCSP-44740
<li><a href=https://deploy-preview-871--app-services.netlify.app/data-api>data-api</a></li><li><a href=https://deploy-preview-871--app-services.netlify.app/data-api/examples>data-api/examples</a></li>

(DOCSP-44740) Hide the data API examples

---

.github/workflows/add-netlify-links.yml

update to new Netlify url pattern

---

source/sync/device-sync-deprecation.txt

https://jira.mongodb.org/browse/DOCSP-47176
<li><a href=https://deploy-preview-877--docs-app-services.netlify.app/sync/device-sync-deprecation>sync/device-sync-deprecation</a></li>

Add PowerSync technical guide link

---

.github/workflows/add-netlify-links.yml

Jira ticket: https://jira.mongodb.org/browse/DOCSP-48584

DOCSP-48584 - Update GH action

---

source/sync/device-sync-deprecation.txt

https://jira.mongodb.org/browse/DOCSP-51132

Add Cedalo link
